/* LYCHGATE :: artifacts.js :: v5.3.0 */
(function () {
  'use strict';

  var U=window.LG_UTIL,S=window.LG_STORAGE,G=window.LG_GAME,I=window.LG_IDENTITY;
  var SCHEMA='LYCHGATE_PASSAGE_STONE_2',BATCH_SCHEMA='LYCHGATE_PASSAGE_BATCH_2';
  var HUMAN_HEAD='LYCHGATE-PASSAGE-STONE-2',HUMAN_END='END-LYCHGATE-PASSAGE-STONE',BATCH_HEAD='LYCHGATE-PASSAGE-BATCH-2',BATCH_END='END-LYCHGATE-PASSAGE-BATCH';
  var COMPACT_PREFIX='LG2:',COMPACT_BATCH_PREFIX='LGB2:',LOCAL_INTEGRITY='LYCHGATE-LOCAL-HASH-24',FRAME_PREFIX='LQF1';

  function worldSaltId(){return 'WS-'+U.hash32('LYCHGATE|WORLD|'+String(S.state.world.salt||'')).toString(16).padStart(8,'0').toUpperCase();}
  function actor(){var card=I.publicCard(),status=I.status();return{id:U.safeText(S.state.player.id,120),callSign:U.safeText(S.state.player.callSign||'Walker',80),faction:S.state.player.faction||null,degree:U.clamp(Number(S.state.player.degree)||1,1,8),keyId:status.ready?card.keyId:null,fingerprint:status.ready?card.fingerprint:null};}
  function artifactHash(value){return U.hash32(U.stableStringify(value)).toString(16).padStart(8,'0')+U.hash32('2|'+U.stableStringify(value)).toString(16).padStart(8,'0');}
  function artifactId(type,stateHash){return 'ps2-'+String(type||'artifact').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'-'+Date.now().toString(36)+'-'+String(stateHash||'00000000').slice(0,8);}
  function provenanceArray(list){return(Array.isArray(list)?list:[]).slice(-11).map(function(p){return{id:U.safeText(p.id,120),at:p.at||null,actorId:U.safeText(p.actorId||'',120),actionType:U.safeText(p.actionType||'',80),stateHash:U.safeText(p.stateHash||'',80)};});}
  function latestActionType(rec){var h=rec&&Array.isArray(rec.history)&&rec.history.length?rec.history[rec.history.length-1]:null;return h&&h.type?U.safeText(h.type,80):'threshold-state';}
  function safeThreshold(t){return{id:U.safeText(t.id,120),name:U.safeText(t.name,160),lat:Number(t.lat),lon:Number(t.lon),kind:U.safeText(t.kind||'generic',50)};}
  function thresholdRecordSnapshot(rec){return{vigils:(rec.vigils||[]).slice(0,8).map(function(v,idx){return{slot:idx,faction:v.faction==='kindled'?'kindled':'sextons',condition:U.clamp(Number(v.condition)||0,0,100),setAt:v.setAt||null};}),petitionCount:Math.max(0,Number(rec.petitionCount)||0),bestSigil:U.clamp(Number(rec.bestSigil)||0,0,100),updatedAt:rec.updatedAt||U.isoNow(),state:G.thresholdStateFor(rec),provenance:U.safeText(rec.provenance||'local record',80)};}
  function latestProvenance(target){return provenanceArray(target&&target.artifactProvenance);}
  function localSign(env){var signer=U.safeText(S.state.identity&&S.state.identity.legacySigner||'',120);env.integrity={method:LOCAL_INTEGRITY,signer:signer,signature:U.simpleSignature(env.payload,signer)};return env;}
  async function signEnvelope(env){if(I.status().ready){env.integrity=await I.signPayload(env.payload);return env;}return localSign(env);}
  async function verifyEnvelope(env){
    if(!env||env.schema!==SCHEMA||Number(env.version)!==2||!env.payload)throw new Error('Passage Stone 2 schema is invalid.');
    if(!env.payload.artifactId||!env.payload.artifactType||!env.payload.timestamp||!env.payload.stateHash)throw new Error('Passage Stone is missing required artifact fields.');
    if(artifactHash(env.payload.state)!==env.payload.stateHash)throw new Error('Passage Stone state hash does not match its state payload.');
    if(!env.integrity)throw new Error('Passage Stone has no integrity record.');
    if(env.integrity.method===LOCAL_INTEGRITY){if(U.simpleSignature(env.payload,env.integrity.signer)!==env.integrity.signature)throw new Error('Passage Stone local integrity stamp does not match its payload.');return{envelope:env,valid:true,cryptographic:false,method:LOCAL_INTEGRITY,reason:'Local integrity stamp verified. It does not establish player identity.',fingerprint:null};}
    if(env.integrity.method===I.method){var result=await I.verifyPayload(env.payload,env.integrity);if(!result.valid)throw new Error(result.reason);return{envelope:env,valid:true,cryptographic:true,method:I.method,reason:result.reason,fingerprint:result.fingerprint,keyId:result.keyId};}
    throw new Error('Passage Stone integrity method is unsupported.');
  }
  async function makeEnvelope(opts){var state=U.deepClone(opts.state),stateHash=artifactHash(state),a=actor(),id=artifactId(opts.artifactType,stateHash),prov=provenanceArray(opts.provenance),timestamp=opts.timestamp||U.isoNow();prov.push({id:id,at:timestamp,actorId:a.id,actionType:opts.actionType||opts.artifactType,stateHash:stateHash});return signEnvelope({schema:SCHEMA,version:2,payload:{artifactId:id,artifactVersion:2,artifactType:opts.artifactType,actionType:opts.actionType||opts.artifactType,timestamp:timestamp,worldSaltId:worldSaltId(),actor:a,threshold:opts.threshold?safeThreshold(opts.threshold):null,previousStateHash:opts.previousStateHash||null,stateHash:stateHash,state:state,provenance:prov}});}
  function rememberOutgoing(env,label){var row={artifactId:env.payload.artifactId,artifactType:env.payload.artifactType,actionType:env.payload.actionType,thresholdId:env.payload.threshold&&env.payload.threshold.id||null,label:U.safeText(label||env.payload.artifactType,160),at:env.payload.timestamp,stateHash:env.payload.stateHash,worldSaltId:env.payload.worldSaltId,integrityMethod:env.integrity.method,fingerprint:env.integrity.fingerprint||null,envelope:U.deepClone(env)};S.state.artifacts.outgoing.push(row);if(S.state.artifacts.outgoing.length>120)S.state.artifacts.outgoing=S.state.artifacts.outgoing.slice(-120);S.markDirty();return row;}
  async function buildThreshold(threshold,remember){if(!threshold)throw new Error('Select a Threshold first.');var rec=G.stateFor(threshold.id);rec.snapshot=rec.snapshot||safeThreshold(threshold);var env=await makeEnvelope({artifactType:'threshold-state',actionType:latestActionType(rec),timestamp:rec.updatedAt||U.isoNow(),threshold:threshold,previousStateHash:rec.lastArtifactStateHash||null,state:thresholdRecordSnapshot(rec),provenance:latestProvenance(rec)});rec.lastArtifactStateHash=env.payload.stateHash;rec.artifactProvenance=provenanceArray(env.payload.provenance);if(remember!==false)rememberOutgoing(env,threshold.name+' Threshold state');return env;}
  async function buildRelic(relicId,remember){var relic=S.state.relics[relicId]||G.relics().filter(function(r){return r.id===relicId;})[0];if(!relic)throw new Error('Relic not found.');var copy=U.deepClone(S.ensureRelic(relic,relic.thresholdId,S.state)),now=U.isoNow();copy.transferCount=Math.max(0,Number(copy.transferCount)||0)+1;copy.history=Array.isArray(copy.history)?copy.history:[];copy.history.push({id:U.randomId('relic-hist'),type:'transferred-out',at:now,note:'Prepared as a Passage Stone 2 transfer.'});var th=G.getThresholdById(copy.thresholdId,G.lastNearby)||{},env=await makeEnvelope({artifactType:'relic-transfer',actionType:'relic-transfer',timestamp:now,threshold:{id:copy.thresholdId,name:copy.thresholdName,lat:th.lat,lon:th.lon,kind:copy.kind},previousStateHash:copy.lastArtifactStateHash||null,state:copy,provenance:latestProvenance(copy)});copy.lastArtifactStateHash=env.payload.stateHash;copy.artifactProvenance=provenanceArray(env.payload.provenance);S.softArchive('relic-transfer',copy.thresholdName+' Relic transferred out',U.deepClone(relic));delete S.state.relics[relic.thresholdId];S.addAction('relic-transfer-out',{relicId:relic.id,thresholdId:relic.thresholdId,thresholdName:relic.thresholdName,transferCount:copy.transferCount,artifactId:env.payload.artifactId});if(remember!==false)rememberOutgoing(env,copy.thresholdName+' Relic transfer');S.markDirty();return env;}
  async function buildIdentity(remember){var card=I.publicCard();if(!I.status().ready)throw new Error('Cryptographic identity is not ready.');var env=await makeEnvelope({artifactType:'identity-card',actionType:'identity-introduction',state:card});if(remember!==false)rememberOutgoing(env,(card.callSign||'Walker')+' identity card');return env;}
  async function buildRiteWitness(remember){var h=S.state.player.riteHistory||[];if(!h.length)throw new Error('No worked Rite is available to witness.');var rite=U.deepClone(h[h.length-1]),t=rite.thresholdId?G.getThresholdById(rite.thresholdId,G.lastNearby):null,env=await makeEnvelope({artifactType:'rite-witness',actionType:'rite-witness',threshold:t||null,state:rite});if(remember!==false)rememberOutgoing(env,(rite.name||'Rite')+' witness');return env;}
  async function buildTerritory(remember){var d=G.groundDominance(),state={capturedAt:U.isoNow(),faction:S.state.player.faction,areas:d.areas,weighted:d.weighted,leader:d.leader,activeLines:S.state.links.filter(function(l){return Number(l.stability)>5;}).length,activeShrouds:d.shrouds.length,shrouds:d.shrouds.slice(0,80).map(function(x){return{id:x.id,faction:x.faction,areaM2:Math.round(x.areaM2),stability:Math.round(x.stability),ids:x.ids};})},env=await makeEnvelope({artifactType:'territory-state',actionType:'territory-witness',state:state});if(remember!==false)rememberOutgoing(env,'Territory witness');return env;}
  async function buildFieldReport(remember){var r=G.fieldReport(),state={capturedAt:U.isoNow(),sessionId:r.session.id,sessionNumber:r.journal.number,startedAt:r.session.startedAt,distanceM:Math.round(r.journal.distanceM),durationMs:Math.round(r.journal.durationMs),regions:r.journal.regions,thresholdsDiscovered:r.journal.thresholdsDiscovered,petitions:r.journal.petitions,sigils:r.journal.sigils,vigils:r.journal.vigils,rites:r.journal.rites,encounters:r.journal.encounters,lines:r.journal.lines,held:r.held,shrouds:r.shrouds,groundArea:r.groundArea},env=await makeEnvelope({artifactType:'field-report',actionType:'field-report',state:state});if(remember!==false)rememberOutgoing(env,'Field report '+String(r.journal.number).padStart(4,'0'));return env;}
  async function buildChallenge(text,remember){text=U.safeText(text,600);if(!text)throw new Error('Write a short challenge or rendezvous note first.');var env=await makeEnvelope({artifactType:'challenge-note',actionType:'challenge',state:{text:text,createdAt:U.isoNow()}});if(remember!==false)rememberOutgoing(env,'Challenge note');return env;}
  async function buildBatch(remember){var envs=[];var ids=Object.keys(S.state.thresholds||{}).sort();for(var i=0;i<ids.length;i+=1){var rec=S.state.thresholds[ids[i]];if(rec&&rec.snapshot&&rec.updatedAt)envs.push(await buildThreshold(rec.snapshot,false));}if(!envs.length)throw new Error('No worked Threshold records are available for a batch.');if(envs.length>80)envs=envs.slice(-80);var summary={batchId:'pb2-'+Date.now().toString(36)+'-'+U.randomId('b').split('-').pop(),createdAt:U.isoNow(),worldSaltId:worldSaltId(),stoneIds:envs.map(function(e){return e.payload.artifactId;})},batch={schema:BATCH_SCHEMA,version:2,batchId:summary.batchId,createdAt:summary.createdAt,worldSaltId:summary.worldSaltId,actor:actor(),stones:envs};batch.integrity=I.status().ready?await I.signPayload(summary):{method:LOCAL_INTEGRITY,signer:S.state.identity.legacySigner,signature:U.simpleSignature(summary,S.state.identity.legacySigner)};if(remember!==false){S.state.artifacts.outgoingBatches.push({batchId:batch.batchId,at:batch.createdAt,count:envs.length,worldSaltId:batch.worldSaltId,integrityMethod:batch.integrity.method});if(S.state.artifacts.outgoingBatches.length>40)S.state.artifacts.outgoingBatches=S.state.artifacts.outgoingBatches.slice(-40);envs.forEach(function(e){rememberOutgoing(e,(e.payload.threshold&&e.payload.threshold.name||'Threshold')+' batch state');});S.markDirty();}return batch;}
  function encodeEnvelope(env,encoding){var compact=COMPACT_PREFIX+U.utf8ToBase64Url(JSON.stringify(env));if(encoding==='compact')return compact;var p=env.payload;return[HUMAN_HEAD,'Artifact: '+p.artifactId,'Version: 2','Type: '+p.artifactType,'Action: '+p.actionType,'Actor: '+(p.actor.callSign||'Walker')+' ['+p.actor.id+']','Order: '+(p.actor.faction||'UNSWORN'),'Degree: '+p.actor.degree,'Identity: '+(p.actor.fingerprint||'UNVERIFIED'),'Threshold: '+(p.threshold?p.threshold.name+' ['+p.threshold.id+']':'None'),'Time: '+p.timestamp,'World: '+p.worldSaltId,'Previous: '+(p.previousStateHash||'NONE'),'State: '+p.stateHash,'Integrity: '+env.integrity.method,'Data: '+U.utf8ToBase64Url(JSON.stringify(env)),HUMAN_END].join('\n');}
  function encodeBatch(batch,encoding){var data=U.utf8ToBase64Url(JSON.stringify(batch));if(encoding==='compact')return COMPACT_BATCH_PREFIX+data;return[BATCH_HEAD,'Batch: '+batch.batchId,'Version: 2','Count: '+batch.stones.length,'World: '+batch.worldSaltId,'Created: '+batch.createdAt,'Integrity: '+(batch.integrity&&batch.integrity.method||'NONE'),'Data: '+data,BATCH_END].join('\n');}
  function decodeBase64Json(data,label){try{return JSON.parse(U.base64UrlToUtf8(data));}catch(e){throw new Error((label||'Artifact')+' payload could not be decoded.');}}
  function parseOne(text){var clean=String(text||'').trim(),env,match;if(clean.indexOf(COMPACT_PREFIX)===0){env=decodeBase64Json(clean.slice(COMPACT_PREFIX.length),'Compact Passage Stone');return{kind:'stone',envelopes:[env],encoding:'compact'};}if(clean.indexOf(COMPACT_BATCH_PREFIX)===0)return parseBatchObject(decodeBase64Json(clean.slice(COMPACT_BATCH_PREFIX.length),'Compact Passage batch'),'compact');if(clean.indexOf(HUMAN_HEAD)===0){match=clean.match(/(?:^|\n)Data:\s*([A-Za-z0-9_-]+)(?:\n|$)/);if(!match)throw new Error('Passage Stone 2 is missing its Data line.');return{kind:'stone',envelopes:[decodeBase64Json(match[1],'Passage Stone')],encoding:'human'};}if(clean.indexOf(BATCH_HEAD)===0){match=clean.match(/(?:^|\n)Data:\s*([A-Za-z0-9_-]+)(?:\n|$)/);if(!match)throw new Error('Passage batch is missing its Data line.');return parseBatchObject(decodeBase64Json(match[1],'Passage batch'),'human');}if(/^LYCHGATE-STONE-1/.test(clean)||/^LYCHGATE-RELIC-1/.test(clean))return{kind:'legacy',envelopes:[],encoding:'legacy',legacyText:clean};throw new Error('Unrecognized Passage Stone format.');}
  function parseBatchObject(batch,encoding){if(!batch||batch.schema!==BATCH_SCHEMA||Number(batch.version)!==2||!Array.isArray(batch.stones))throw new Error('Passage batch schema is invalid.');return{kind:'batch',batch:batch,envelopes:batch.stones,encoding:encoding};}
  async function verifyBatch(batch){var summary={batchId:batch.batchId,createdAt:batch.createdAt,worldSaltId:batch.worldSaltId,stoneIds:batch.stones.map(function(e){return e.payload.artifactId;})};if(!batch.integrity)return{valid:false,reason:'Batch has no integrity record.'};if(batch.integrity.method===LOCAL_INTEGRITY){if(U.simpleSignature(summary,batch.integrity.signer)!==batch.integrity.signature)throw new Error('Passage batch local integrity stamp does not match its contents.');return{valid:true,cryptographic:false};}var v=await I.verifyPayload(summary,batch.integrity);if(!v.valid)throw new Error(v.reason);return{valid:true,cryptographic:true,fingerprint:v.fingerprint};}
  function registryKey(env,verification){var p=env.payload,fp=verification&&verification.fingerprint||env.integrity&&env.integrity.fingerprint||p.actor&&p.actor.fingerprint;return fp||('LEGACY '+U.hash32((p.actor&&p.actor.id)||'unknown').toString(16).toUpperCase());}
  function registryEntryFor(env,verification){return S.state.registry[registryKey(env,verification)]||null;}
  function localThresholdComparison(env,policy){var p=env.payload,t=p.threshold,rec=t?S.state.thresholds[t.id]:null,localAt=rec&&rec.updatedAt?new Date(rec.updatedAt).getTime():0,inAt=new Date(p.timestamp||0).getTime(),hasLocal=!!(rec&&rec.updatedAt),decision='incoming';if(hasLocal){if(policy==='keep-local')decision='local';else if(policy==='accept-incoming')decision='incoming';else decision=inAt>localAt?'incoming':'local';}return{hasLocal:hasLocal,decision:decision,record:rec||null};}
  function localRelicComparison(env,policy){var incoming=env.payload.state,existing=incoming&&S.state.relics[incoming.thresholdId],decision='incoming';if(existing){var inAt=new Date(env.payload.timestamp||0).getTime(),exHist=existing.history&&existing.history.length?existing.history[existing.history.length-1].at:existing.foundAt,exAt=new Date(exHist||0).getTime();if(policy==='keep-local')decision='local';else if(policy==='accept-incoming')decision='incoming';else decision=inAt>exAt?'incoming':'local';return{hasLocal:true,decision:decision,record:existing};}return{hasLocal:false,decision:'incoming',record:null};}
  async function inspectEnvelope(env,options){var verification=await verifyEnvelope(env);options=options||{};var p=env.payload,seen=S.state.artifacts.seen[p.artifactId],sameState=S.state.artifacts.stateHashes[p.stateHash],worldMatch=p.worldSaltId===worldSaltId(),cmp=p.artifactType==='threshold-state'?localThresholdComparison(env,options.policy):p.artifactType==='relic-transfer'?localRelicComparison(env,options.policy):{hasLocal:false,decision:'incoming'},entry=registryEntryFor(env,verification),status='READY',reason=verification.reason;if(entry&&entry.trust==='blocked'){status='BLOCKED ACTOR';reason='This identity fingerprint is blocked in the local Registry.';}else if(seen){status='DUPLICATE';reason='This artifact ID has already been committed.';}else if(sameState){status='DUPLICATE STATE';reason='An artifact with the same state hash has already been committed.';}else if(!worldMatch&&!options.allowWorldMismatch&&['identity-card','challenge-note','field-report'].indexOf(p.artifactType)<0){status='WORLD MISMATCH';reason='The artifact belongs to '+p.worldSaltId+', while this save uses '+worldSaltId()+'.';}else if(cmp.hasLocal){status=cmp.decision==='incoming'?'CONFLICT: INCOMING WINS':'CONFLICT: LOCAL WINS';reason=(options.policy==='timestamp'||!options.policy?'Timestamp policy selected. ':'Manual conflict policy selected. ')+verification.reason;}return{artifactId:p.artifactId,artifactType:p.artifactType,actionType:p.actionType,timestamp:p.timestamp,worldSaltId:p.worldSaltId,worldMatch:worldMatch,actor:p.actor,threshold:p.threshold,previousStateHash:p.previousStateHash,stateHash:p.stateHash,provenanceDepth:(p.provenance||[]).length,status:status,reason:reason,decision:cmp.decision||'incoming',blocked:status==='BLOCKED ACTOR'||!!seen||!!sameState||(!worldMatch&&!options.allowWorldMismatch&&['identity-card','challenge-note','field-report'].indexOf(p.artifactType)<0),duplicate:!!seen||!!sameState,cryptographic:verification.cryptographic,fingerprint:registryKey(env,verification),verification:verification,envelope:env};}
  async function preview(text,options){var parsed=parseOne(text),items=[];if(parsed.kind==='legacy')return{kind:'legacy',encoding:'legacy',legacy:true,summary:'Legacy Passage Stone. It will use the v1 compatibility importer when committed.',items:[{status:'LEGACY',reason:'Verified during commit by the original v1 importer.',blocked:false,legacy:true}]};if(parsed.kind==='batch')await verifyBatch(parsed.batch);for(var i=0;i<parsed.envelopes.length;i+=1)items.push(await inspectEnvelope(parsed.envelopes[i],options||{}));return{kind:parsed.kind,encoding:parsed.encoding,batchId:parsed.batch&&parsed.batch.batchId||null,items:items,valid:items.every(function(x){return !x.blocked;}),summary:items.length+' artifact'+(items.length===1?'':'s')+' inspected.',parsed:parsed};}
  function updateRegistry(env,verification,result){var p=env.payload,a=p.actor||{},key=registryKey(env,verification),now=U.isoNow(),r=S.state.registry[key]||{fingerprint:key,firstSeen:now,trust:'unknown',notes:'',artifactCount:0,thresholdIds:[],relicCount:0};r.lastSeen=now;r.playerId=U.safeText(a.id||'',120);r.callSign=U.safeText(a.callSign||'Unknown walker',80);r.faction=a.faction||null;r.degree=U.clamp(Number(a.degree)||1,1,8);r.keyId=env.integrity&&env.integrity.keyId||a.keyId||r.keyId||null;r.publicJwk=env.integrity&&env.integrity.publicJwk?U.deepClone(env.integrity.publicJwk):r.publicJwk||null;r.signatureStatus=verification.cryptographic?'verified':'local-integrity';r.artifactCount+=1;r.lastArtifactType=p.artifactType;r.lastResult=result;if(p.threshold&&p.threshold.id&&r.thresholdIds.indexOf(p.threshold.id)<0)r.thresholdIds.push(p.threshold.id);if(r.thresholdIds.length>120)r.thresholdIds=r.thresholdIds.slice(-120);if(p.artifactType==='relic-transfer')r.relicCount+=1;if(p.artifactType==='territory-state')r.lastTerritoryAt=p.timestamp;if(p.artifactType==='identity-card'&&p.state){r.callSign=U.safeText(p.state.callSign||r.callSign,80);r.playerId=U.safeText(p.state.playerId||r.playerId,120);r.faction=p.state.faction||r.faction;r.degree=U.clamp(Number(p.state.degree)||r.degree,1,8);}S.state.registry[key]=r;return r;}
  function markSeen(env,result,verification){var p=env.payload,row={artifactId:p.artifactId,artifactType:p.artifactType,actionType:p.actionType,importedAt:U.isoNow(),sourceTimestamp:p.timestamp,worldSaltId:p.worldSaltId,stateHash:p.stateHash,actor:U.deepClone(p.actor),threshold:p.threshold?U.deepClone(p.threshold):null,result:result,integrityMethod:env.integrity.method,fingerprint:registryKey(env,verification),signatureStatus:verification.cryptographic?'verified':'local-integrity'};S.state.artifacts.seen[p.artifactId]=row;S.state.artifacts.stateHashes[p.stateHash]=p.artifactId;S.state.artifacts.incoming.push(row);if(S.state.artifacts.incoming.length>250)S.state.artifacts.incoming=S.state.artifacts.incoming.slice(-250);S.state.importedStones.push({importedAt:row.importedAt,signer:row.fingerprint,thresholdId:p.threshold&&p.threshold.id||null,signature:env.integrity.signature,type:'passage-stone-2',artifactId:p.artifactId,result:result});updateRegistry(env,verification,result);return row;}
  function applyThreshold(env,decision){var p=env.payload,t=p.threshold;if(!t||!t.id||!isFinite(t.lat)||!isFinite(t.lon))throw new Error('Threshold artifact is missing usable coordinates.');var rec=G.stateFor(t.id),incoming=U.deepClone(p.state),loser=null;if(decision==='local'){loser={side:'incoming',record:incoming,artifactId:p.artifactId,at:p.timestamp};S.softArchive('artifact-conflict-loser',t.name+' incoming Threshold state',loser);rec.history.push({id:U.randomId('hist'),type:'stone-conflict',at:U.isoNow(),winner:'local',loser:loser,provenance:'passage stone 2'});return{result:'local-kept',name:t.name,thresholdId:t.id};}if(rec.updatedAt){loser={side:'local',record:U.deepClone({snapshot:rec.snapshot,vigils:rec.vigils,petitionCount:rec.petitionCount,bestSigil:rec.bestSigil,updatedAt:rec.updatedAt}),at:rec.updatedAt};S.softArchive('artifact-conflict-loser',t.name+' local Threshold state',loser);}rec.snapshot={id:t.id,name:t.name,lat:Number(t.lat),lon:Number(t.lon),kind:t.kind||'generic',provenance:'passage stone 2'};rec.provenance='passage stone 2';rec.vigils=Array.isArray(incoming.vigils)?incoming.vigils.slice(0,8).map(function(v,idx){return{slot:idx,faction:v.faction==='kindled'?'kindled':'sextons',condition:U.clamp(Number(v.condition)||0,0,100),currentCondition:U.clamp(Number(v.condition)||0,0,100),setAt:v.setAt||p.timestamp};}):[];rec.petitionCount=Math.max(0,Number(incoming.petitionCount)||0);rec.bestSigil=U.clamp(Number(incoming.bestSigil)||0,0,100);rec.updatedAt=incoming.updatedAt||p.timestamp;rec.lastArtifactStateHash=p.stateHash;rec.artifactProvenance=provenanceArray(p.provenance);rec.history.push({id:U.randomId('hist'),type:loser?'stone-conflict':'stone-import',at:U.isoNow(),winner:'incoming',artifactId:p.artifactId,provenance:'passage stone 2'});return{result:loser?'incoming-won':'imported',name:t.name,thresholdId:t.id};}
  function applyRelic(env,decision){var p=env.payload,incoming=S.ensureRelic(U.deepClone(p.state),p.state.thresholdId,S.state),existing=S.state.relics[incoming.thresholdId];if(decision==='local'&&existing){S.softArchive('artifact-conflict-loser',incoming.thresholdName+' incoming Relic state',{side:'incoming',record:incoming,artifactId:p.artifactId,at:p.timestamp});return{result:'local-kept',name:incoming.thresholdName,thresholdId:incoming.thresholdId,type:'relic'};}if(existing)S.softArchive('artifact-conflict-loser',existing.thresholdName+' local Relic state',{side:'local',record:U.deepClone(existing),at:existing.foundAt});incoming.transferCount=Math.max(1,Number(incoming.transferCount)||1);incoming.lastArtifactStateHash=p.stateHash;incoming.artifactProvenance=provenanceArray(p.provenance);incoming.history=Array.isArray(incoming.history)?incoming.history:[];incoming.history.push({id:U.randomId('relic-hist'),type:'transferred-in',at:U.isoNow(),note:'Imported through Passage Stone 2 from '+U.safeText(p.actor.callSign||p.actor.id,80)+'.'});S.state.relics[incoming.thresholdId]=incoming;return{result:existing?'incoming-won':'imported',name:incoming.thresholdName,thresholdId:incoming.thresholdId,type:'relic'};}
  function applyInformational(env){var p=env.payload,label=(p.actor&&p.actor.callSign||'Walker')+' '+p.artifactType.replace(/-/g,' ');S.softArchive('artifact-evidence',label,{artifactId:p.artifactId,actor:p.actor,timestamp:p.timestamp,state:p.state,integrity:env.integrity});return{result:'registered',name:label,type:p.artifactType};}
  async function commit(text,options){options=Object.assign({policy:'timestamp',allowWorldMismatch:false},options||{});var parsed=parseOne(text),results=[];if(parsed.kind==='legacy'){var clean=parsed.legacyText,r=/^LYCHGATE-RELIC-1/.test(clean)?G.importRelicStone(clean):G.importStone(clean);return{kind:'legacy',results:[r],committed:1,skipped:0};}if(parsed.kind==='batch')await verifyBatch(parsed.batch);for(var i=0;i<parsed.envelopes.length;i+=1){var env=parsed.envelopes[i],inspect=await inspectEnvelope(env,options),p=env.payload;if(inspect.blocked){results.push({artifactId:p.artifactId,status:'skipped',reason:inspect.reason});continue;}var r;if(p.artifactType==='threshold-state')r=applyThreshold(env,inspect.decision);else if(p.artifactType==='relic-transfer')r=applyRelic(env,inspect.decision);else r=applyInformational(env);markSeen(env,r.result,inspect.verification);S.addAction('stone-import',{artifactId:p.artifactId,artifactType:p.artifactType,thresholdId:p.threshold&&p.threshold.id||null,fingerprint:inspect.fingerprint,result:r.result});results.push(Object.assign({artifactId:p.artifactId,status:'committed'},r));}S.markDirty();return{kind:parsed.kind,results:results,committed:results.filter(function(r){return r.status==='committed';}).length,skipped:results.filter(function(r){return r.status==='skipped';}).length};}
  function qrMatrix(text){if(!window.LG_QR||!window.LG_QR.QRCode)throw new Error('Local QR encoder is unavailable.');var q=new window.LG_QR.QRCode(0,window.LG_QR.ErrorCorrectLevel.L);q.addData(String(text));q.make();var size=q.getModuleCount(),rows=[];for(var y=0;y<size;y+=1){var row=[];for(var x=0;x<size;x+=1)row.push(q.isDark(y,x));rows.push(row);}return rows;}
  function drawQR(canvas,text){var rows=qrMatrix(text),quiet=4,count=rows.length,total=count+quiet*2,rect=canvas.getBoundingClientRect(),px=Math.max(256,Math.min(768,Math.floor(rect.width||420))),module=Math.max(2,Math.floor(px/total)),size=module*total;canvas.width=size;canvas.height=size;var ctx=canvas.getContext('2d');ctx.fillStyle='#efe4cc';ctx.fillRect(0,0,size,size);ctx.fillStyle='#090807';for(var y=0;y<count;y+=1)for(var x=0;x<count;x+=1)if(rows[y][x])ctx.fillRect((x+quiet)*module,(y+quiet)*module,module,module);return{modules:count,size:size};}
  function makeQrFrames(text,maxChunk){var encoded=U.utf8ToBase64Url(String(text||'')),chunk=Math.max(240,Math.min(900,Number(maxChunk)||620)),total=Math.ceil(encoded.length/chunk),session='qf-'+Date.now().toString(36)+'-'+U.randomId('q').split('-').pop(),sum=artifactHash(String(text||'')).slice(0,12),frames=[];for(var i=0;i<total;i+=1)frames.push([FRAME_PREFIX,session,i+1,total,sum,encoded.slice(i*chunk,(i+1)*chunk)].join('|'));return{session:session,total:total,checksum:sum,frames:frames};}
  function parseQrFrame(text){var p=String(text||'').split('|');if(p.length!==6||p[0]!==FRAME_PREFIX)throw new Error('Not a LYCHGATE QR frame.');var index=Number(p[2]),total=Number(p[3]);if(!(index>=1&&total>=1&&index<=total&&total<=64))throw new Error('QR frame numbering is invalid.');return{session:p[1],index:index,total:total,checksum:p[4],chunk:p[5]};}
  function joinQrFrames(frameMap){var keys=Object.keys(frameMap||{});if(!keys.length)throw new Error('No QR frames collected.');var first=frameMap[keys[0]],parts=[];for(var i=1;i<=first.total;i+=1){var f=frameMap[i];if(!f)throw new Error('QR frame '+i+' of '+first.total+' is still missing.');if(f.session!==first.session||f.total!==first.total||f.checksum!==first.checksum)throw new Error('QR frames belong to different exchanges.');parts.push(f.chunk);}var text=U.base64UrlToUtf8(parts.join(''));if(artifactHash(text).slice(0,12)!==first.checksum)throw new Error('Reassembled QR exchange checksum failed.');return text;}
  function registry(){return Object.keys(S.state.registry||{}).map(function(k){return S.state.registry[k];}).sort(function(a,b){return new Date(b.lastSeen)-new Date(a.lastSeen);});}
  function setRegistryTrust(fingerprint,trust){if(['unknown','known','trusted','blocked'].indexOf(trust)<0)throw new Error('Unsupported Registry trust state.');var r=S.state.registry[fingerprint];if(!r)throw new Error('Registry identity not found.');r.trust=trust;r.trustChangedAt=U.isoNow();S.markDirty();return r;}
  function setRegistryNotes(fingerprint,notes){var r=S.state.registry[fingerprint];if(!r)throw new Error('Registry identity not found.');r.notes=U.safeText(notes,1200);S.markDirty();return r;}
  function artifactRegister(){return{incoming:(S.state.artifacts.incoming||[]).slice().reverse(),outgoing:(S.state.artifacts.outgoing||[]).slice().reverse(),batches:(S.state.artifacts.outgoingBatches||[]).slice().reverse()};}

  window.LG_ARTIFACTS={schema:SCHEMA,batchSchema:BATCH_SCHEMA,worldSaltId:worldSaltId,artifactHash:artifactHash,buildThreshold:buildThreshold,buildRelic:buildRelic,buildIdentity:buildIdentity,buildRiteWitness:buildRiteWitness,buildTerritory:buildTerritory,buildFieldReport:buildFieldReport,buildChallenge:buildChallenge,buildBatch:buildBatch,encodeEnvelope:encodeEnvelope,encodeBatch:encodeBatch,parse:parseOne,preview:preview,commit:commit,verifyEnvelope:verifyEnvelope,qrMatrix:qrMatrix,drawQR:drawQR,makeQrFrames:makeQrFrames,parseQrFrame:parseQrFrame,joinQrFrames:joinQrFrames,registry:registry,setRegistryTrust:setRegistryTrust,setRegistryNotes:setRegistryNotes,register:artifactRegister,compactPrefix:COMPACT_PREFIX,compactBatchPrefix:COMPACT_BATCH_PREFIX,integrityMethod:I.method,localIntegrityMethod:LOCAL_INTEGRITY};
}());
