/* LYCHGATE :: expeditions.js :: v5.3.0 */
(function(){
  'use strict';
  var U=window.LG_UTIL,S=window.LG_STORAGE,W=window.LG_WORLD,G=window.LG_GAME;
  var VALID=['planned','ready','underway','paused','completed','abandoned'];
  function store(){if(!S.state.expeditions||typeof S.state.expeditions!=='object')S.state.expeditions={items:{},order:[],activeId:null};if(!S.state.expeditions.items)S.state.expeditions.items={};if(!Array.isArray(S.state.expeditions.order))S.state.expeditions.order=[];return S.state.expeditions;}
  function point(p,label){if(!p||!isFinite(Number(p.lat))||!isFinite(Number(p.lon)))return null;return{lat:Number(p.lat),lon:Number(p.lon),label:U.safeText(label||p.label||'',120),at:p.at||U.isoNow()};}
  function ensure(exp){exp=exp&&typeof exp==='object'?exp:{};exp.id=exp.id||U.randomId('exp');exp.title=U.safeText(exp.title||'Untitled Expedition',120);exp.purpose=U.safeText(exp.purpose||'',1200);exp.status=VALID.indexOf(exp.status)>=0?exp.status:'planned';exp.createdAt=exp.createdAt||U.isoNow();exp.updatedAt=exp.updatedAt||exp.createdAt;exp.startPoint=point(exp.startPoint,'Start');exp.returnPoint=point(exp.returnPoint,'Return');exp.route=Array.isArray(exp.route)?exp.route.map(function(p){return point(p,p.label);}).filter(Boolean):[];exp.checkpoints=Array.isArray(exp.checkpoints)?exp.checkpoints.map(function(c){var p=point(c,c.name||c.label);if(!p)return null;p.id=c.id||U.randomId('cp');p.name=U.safeText(c.name||c.label||'Checkpoint',100);p.notes=U.safeText(c.notes||'',500);p.doneAt=c.doneAt||null;return p;}).filter(Boolean):[];exp.thresholdIds=Array.isArray(exp.thresholdIds)?exp.thresholdIds.slice(0,100):[];exp.unexploredCells=Array.isArray(exp.unexploredCells)?exp.unexploredCells.slice(0,100):[];exp.companions=Array.isArray(exp.companions)?exp.companions.map(function(x){return U.safeText(x,80);}).filter(Boolean).slice(0,30):[];exp.requiredRelics=Array.isArray(exp.requiredRelics)?exp.requiredRelics.slice(0,60):[];exp.plannedRites=Array.isArray(exp.plannedRites)?exp.plannedRites.slice(0,60):[];exp.safetyNotes=U.safeText(exp.safetyNotes||'',1600);exp.estimatedMinutes=Math.max(0,Math.min(1440,Number(exp.estimatedMinutes)||0));exp.timeline=Array.isArray(exp.timeline)?exp.timeline:[];exp.track=Array.isArray(exp.track)?exp.track:[];exp.startedAt=exp.startedAt||null;exp.pausedAt=exp.pausedAt||null;exp.completedAt=exp.completedAt||null;exp.abandonedAt=exp.abandonedAt||null;exp.replay=exp.replay&&typeof exp.replay==='object'?exp.replay:null;return exp;}
  function get(id){var e=store().items[id];return e?ensure(e):null;}
  function active(){var st=store();return st.activeId?get(st.activeId):null;}
  function routeDistance(exp){exp=ensure(exp);var pts=[];if(exp.startPoint)pts.push(exp.startPoint);pts=pts.concat(exp.route);if(exp.returnPoint)pts.push(exp.returnPoint);var total=0;for(var i=1;i<pts.length;i+=1)total+=U.distanceM(pts[i-1],pts[i]);return total;}
  function visitedCellSet(){var out={};(S.state.position.history||[]).forEach(function(f){if(isFinite(f.lat)&&isFinite(f.lon))out[W.geohashEncode(f.lat,f.lon,6)]=true;});return out;}
  function computeUnknown(exp){var known=visitedCellSet(),cells={};function add(p){if(p)cells[W.geohashEncode(p.lat,p.lon,6)]=true;}add(exp.startPoint);exp.route.forEach(add);exp.checkpoints.forEach(add);add(exp.returnPoint);return Object.keys(cells).filter(function(c){return !known[c];});}
  function knownThresholds(exp){return exp.thresholdIds.map(function(id){return G.getThresholdById(id,G.lastNearby)||((S.state.thresholds[id]||{}).snapshot);}).filter(Boolean);}
  function create(opts){opts=opts||{};var fix=S.state.position.fix,home=S.state.player.home,st=store();var exp=ensure({title:opts.title||'Field Expedition',purpose:opts.purpose||'',startPoint:opts.startPoint||fix,returnPoint:opts.returnPoint||home||fix,safetyNotes:opts.safetyNotes||'',estimatedMinutes:opts.estimatedMinutes||0,companions:opts.companions||[],thresholdIds:opts.thresholdIds||[],requiredRelics:opts.requiredRelics||[],plannedRites:opts.plannedRites||[]});if(!exp.startPoint)throw new Error('Set a position fix before creating an Expedition.');if(!exp.returnPoint)throw new Error('Set a return point before creating an Expedition.');exp.route=[point(exp.startPoint,'Departure')];exp.unexploredCells=computeUnknown(exp);st.items[exp.id]=exp;st.order.push(exp.id);S.addAction('expedition-create',{expeditionId:exp.id,title:exp.title});S.markDirty();return exp;}
  function update(id,patch){var exp=get(id);if(!exp)throw new Error('Expedition not found.');if(['underway','completed','abandoned'].indexOf(exp.status)>=0)throw new Error('This Expedition cannot be edited in its current state.');patch=patch||{};if(patch.title!=null)exp.title=U.safeText(patch.title,120)||exp.title;if(patch.purpose!=null)exp.purpose=U.safeText(patch.purpose,1200);if(patch.safetyNotes!=null)exp.safetyNotes=U.safeText(patch.safetyNotes,1600);if(patch.estimatedMinutes!=null)exp.estimatedMinutes=Math.max(0,Math.min(1440,Number(patch.estimatedMinutes)||0));if(patch.companions)exp.companions=patch.companions.map(function(x){return U.safeText(x,80);}).filter(Boolean).slice(0,30);if(patch.thresholdIds)exp.thresholdIds=patch.thresholdIds.slice(0,100);if(patch.requiredRelics)exp.requiredRelics=patch.requiredRelics.slice(0,60);if(patch.plannedRites)exp.plannedRites=patch.plannedRites.slice(0,60);exp.unexploredCells=computeUnknown(exp);exp.updatedAt=U.isoNow();S.markDirty();return exp;}
  function addRoutePoint(id,p,label){var exp=get(id);if(!exp)throw new Error('Expedition not found.');if(['completed','abandoned'].indexOf(exp.status)>=0)throw new Error('Closed Expeditions cannot be edited.');p=point(p,label||'Route point');if(!p)throw new Error('A valid current position is required.');exp.route.push(p);if(exp.route.length>500)exp.route=exp.route.slice(-500);exp.unexploredCells=computeUnknown(exp);exp.updatedAt=U.isoNow();S.markDirty();return p;}
  function addCheckpoint(id,p,name,notes){var exp=get(id);if(!exp)throw new Error('Expedition not found.');p=point(p,name||'Checkpoint');if(!p)throw new Error('A valid current position is required.');p.id=U.randomId('cp');p.name=U.safeText(name||'Checkpoint',100);p.notes=U.safeText(notes||'',500);p.doneAt=null;exp.checkpoints.push(p);exp.unexploredCells=computeUnknown(exp);exp.updatedAt=U.isoNow();S.markDirty();return p;}
  function markCheckpoint(id,checkpointId){var exp=get(id),cp=exp&&exp.checkpoints.filter(function(c){return c.id===checkpointId;})[0];if(!cp)throw new Error('Checkpoint not found.');cp.doneAt=cp.doneAt||U.isoNow();exp.timeline.push({id:U.randomId('evt'),kind:'checkpoint',at:cp.doneAt,label:cp.name,data:{checkpointId:cp.id,lat:cp.lat,lon:cp.lon}});S.addAction('expedition-checkpoint',{expeditionId:exp.id,checkpointId:cp.id,name:cp.name});S.markDirty();return cp;}
  function ready(id){var exp=get(id);if(!exp)throw new Error('Expedition not found.');if(exp.status!=='planned')throw new Error('Only a planned Expedition can be marked ready.');if(!exp.startPoint||!exp.returnPoint)throw new Error('Start and return points are required.');if(!exp.safetyNotes)throw new Error('Record a safety note before marking the Expedition ready.');exp.status='ready';exp.readyAt=U.isoNow();exp.updatedAt=exp.readyAt;S.addAction('expedition-ready',{expeditionId:exp.id,title:exp.title});S.markDirty();return exp;}
  function start(id){var st=store(),exp=get(id);if(!exp)throw new Error('Expedition not found.');if(['ready','paused'].indexOf(exp.status)<0)throw new Error('Expedition must be ready or paused to begin.');if(st.activeId&&st.activeId!==id)throw new Error('Another Expedition is already active.');var now=U.isoNow();if(exp.status==='ready'){exp.startedAt=now;exp.track=[];exp.timeline=[];exp.replay=null;exp.timeline.push({id:U.randomId('evt'),kind:'lifecycle',at:now,label:'Expedition started',data:{status:'underway'}});}else exp.timeline.push({id:U.randomId('evt'),kind:'lifecycle',at:now,label:'Expedition resumed',data:{status:'underway'}});exp.status='underway';exp.pausedAt=null;exp.updatedAt=now;st.activeId=id;if(S.state.position.fix)recordFix(S.state.position.fix);S.addAction('expedition-start',{expeditionId:id,title:exp.title});S.markDirty();return exp;}
  function pause(id){var exp=get(id);if(!exp||exp.status!=='underway')throw new Error('Only an underway Expedition can be paused.');var now=U.isoNow();exp.status='paused';exp.pausedAt=now;exp.updatedAt=now;exp.timeline.push({id:U.randomId('evt'),kind:'lifecycle',at:now,label:'Expedition paused',data:{status:'paused'}});S.addAction('expedition-pause',{expeditionId:id});S.markDirty();return exp;}
  function close(id,status){var st=store(),exp=get(id);if(!exp||['underway','paused'].indexOf(exp.status)<0)throw new Error('Only an active Expedition can be closed.');var now=U.isoNow();exp.status=status;exp.updatedAt=now;if(status==='completed')exp.completedAt=now;else exp.abandonedAt=now;exp.timeline.push({id:U.randomId('evt'),kind:'lifecycle',at:now,label:status==='completed'?'Expedition completed':'Expedition abandoned',data:{status:status}});st.activeId=null;exp.replay=buildReplay(exp);S.addAction(status==='completed'?'expedition-complete':'expedition-abandon',{expeditionId:id,title:exp.title,distanceM:exp.replay.distanceM});S.markDirty();return exp;}
  function recordFix(fix){var exp=active();if(!exp||exp.status!=='underway'||!fix)return null;var p=point(fix,'Track fix');p.source=fix.source||S.state.position.source;p.simulated=!!fix.simulated;p.speed=isFinite(fix.speed)?Number(fix.speed):0;var last=exp.track[exp.track.length-1];if(last&&U.distanceM(last,p)<2&&new Date(p.at)-new Date(last.at)<5000)return null;exp.track.push(p);if(exp.track.length>20000)exp.track=exp.track.slice(-20000);exp.updatedAt=p.at;return p;}
  function recordAction(action){var exp=active();if(!exp||exp.status!=='underway'||!action)return null;if(action.type.indexOf('expedition-')===0)return null;var ev={id:action.id||U.randomId('evt'),kind:'action',at:action.at||U.isoNow(),label:action.type,data:U.deepClone(action.data||{})};exp.timeline.push(ev);if(exp.timeline.length>5000)exp.timeline=exp.timeline.slice(-5000);exp.updatedAt=ev.at;return ev;}
  function buildReplay(exp){exp=ensure(exp);var track=exp.track.slice(),events=exp.timeline.slice().sort(function(a,b){return new Date(a.at)-new Date(b.at);}),distance=0;for(var i=1;i<track.length;i+=1){var d=U.distanceM(track[i-1],track[i]);if(d<500)distance+=d;}var started=exp.startedAt?new Date(exp.startedAt).getTime():Date.now(),ended=exp.completedAt?new Date(exp.completedAt).getTime():exp.abandonedAt?new Date(exp.abandonedAt).getTime():Date.now();return{schema:'LYCHGATE_EXPEDITION_REPLAY_1',generatedAt:U.isoNow(),startedAt:exp.startedAt,endedAt:new Date(ended).toISOString(),durationMs:Math.max(0,ended-started),distanceM:distance,track:track,events:events,plannedRoute:[exp.startPoint].concat(exp.route||[]).concat([exp.returnPoint]).filter(Boolean)};}
  function replayAt(exp,fraction){var r=exp&&exp.replay?exp.replay:buildReplay(exp),f=U.clamp(Number(fraction)||0,0,1);if(!r.track.length)return{replay:r,index:0,point:null,events:[]};var idx=Math.min(r.track.length-1,Math.floor(f*(r.track.length-1))),point=r.track[idx],tm=new Date(point.at).getTime();return{replay:r,index:idx,point:point,events:r.events.filter(function(e){return new Date(e.at).getTime()<=tm;})};}
  function list(){var st=store();return st.order.slice().reverse().map(function(id){return get(id);}).filter(Boolean);}
  function summary(exp){exp=ensure(exp);return{distanceM:routeDistance(exp),checkpoints:exp.checkpoints.length,checkpointsDone:exp.checkpoints.filter(function(c){return c.doneAt;}).length,thresholds:knownThresholds(exp).length,unknownCells:exp.unexploredCells.length,routePoints:exp.route.length,trackFixes:exp.track.length,events:exp.timeline.length};}
  function exportRecord(id){var exp=get(id);if(!exp)throw new Error('Expedition not found.');return JSON.stringify({schema:'LYCHGATE_EXPEDITION_1',version:1,appVersion:U.VERSION,worldSaltId:window.LG_ARTIFACTS?window.LG_ARTIFACTS.worldSaltId():null,exportedAt:U.isoNow(),expedition:U.deepClone(exp)},null,2);}
  window.LG_EXPEDITIONS={ensureStore:store,ensure:ensure,create:create,update:update,get:get,list:list,active:active,addRoutePoint:addRoutePoint,addCheckpoint:addCheckpoint,markCheckpoint:markCheckpoint,ready:ready,start:start,pause:pause,complete:function(id){return close(id,'completed');},abandon:function(id){return close(id,'abandoned');},recordFix:recordFix,recordAction:recordAction,routeDistance:routeDistance,computeUnknown:computeUnknown,buildReplay:buildReplay,replayAt:replayAt,summary:summary,exportRecord:exportRecord,statuses:VALID.slice()};
}());
