/* LYCHGATE :: game.js :: v5.3.0 */
(function () {
  'use strict';

  var U=window.LG_UTIL,W=window.LG_WORLD,S=window.LG_STORAGE;

  function stateFor(id) {
    if(!S.state.thresholds[id])S.state.thresholds[id]={id:id,vigils:[],petitionCount:0,bestSigil:0,sigilHistory:[],updatedAt:null,history:[],notes:[],photos:[],rites:[],riteEffects:{},loreWitnesses:[],provenance:String(id).indexOf('th-')===0?'deterministic':'local record',discoveredAt:null};
    return S.ensureRecord(S.state.thresholds[id],id);
  }

  function thresholdSnapshot(t) {
    return{id:t.id,name:t.name,lat:t.lat,lon:t.lon,kind:t.kind,cell:t.cell||null,latent:t.latent||null,provenance:t.provenance||'deterministic',featureBias:t.featureBias||null};
  }

  function decayVigils(record,nowMs) {
    nowMs=Number(nowMs)||Date.now();
    var kind=record.snapshot&&record.snapshot.kind||'generic',rate=.75*(W.featureEffect(kind).decay||1),effects=record.riteEffects||{};
    (record.vigils||[]).forEach(function(v){
      var start=new Date(v.setAt).getTime(),age=Math.max(0,(nowMs-start)/3600000),loss=age*rate;
      var guard=effects.decayGuard;if(guard&&(!guard.faction||guard.faction===v.faction)){var gs=new Date(guard.start||0).getTime(),ge=new Date(guard.until||0).getTime(),protectedH=overlapHours(start,nowMs,gs,ge),mult=U.clamp(Number(guard.multiplier)||1,.25,1);loss-=protectedH*rate*(1-mult);}
      var burden=effects.decayBurden;if(burden&&(!burden.faction||burden.faction===v.faction)){var bs=new Date(burden.start||0).getTime(),be=new Date(burden.until||0).getTime(),burdenH=overlapHours(start,nowMs,bs,be),bmult=Math.max(1,Number(burden.multiplier)||1);loss+=burdenH*rate*(bmult-1);}
      v.currentCondition=U.clamp(v.condition-loss,0,100);
    });
  }

  function factionFromVigils(record) {
    decayVigils(record);var counts={kindled:0,sextons:0};
    (record.vigils||[]).forEach(function(v){if(v.currentCondition>1&&counts[v.faction]!=null)counts[v.faction]+=1;});
    if(counts.kindled>=5&&counts.kindled>counts.sextons)return'kindled';
    if(counts.sextons>=5&&counts.sextons>counts.kindled)return'sextons';return null;
  }

  function practice(points,reason){S.state.player.practiceScore+=points;S.addAction('practice',{points:points,reason:reason});}
  function requireFaction(){if(!S.state.player.faction)throw new Error('Choose an order in Rites before working thresholds.');}

  function getThresholdById(id,nearList){var found=null;(nearList||[]).some(function(t){if(t.id===id){found=t;return true;}return false;});if(found)return found;var rec=S.state.thresholds[id];return rec&&rec.snapshot?rec.snapshot:null;}

  function activeVigils(rec){decayVigils(rec);return(rec.vigils||[]).filter(function(v){return v.currentCondition>1;});}

  function thresholdState(rec) {
    var active=activeVigils(rec), faction=factionFromVigils(rec), enemyKinds={};active.forEach(function(v){enemyKinds[v.faction]=true;});
    if(active.length&&enemyKinds.kindled&&enemyKinds.sextons)return'CONTESTED';
    if(faction==='kindled')return'KINDLED';
    if(faction==='sextons')return'SEALED';
    if(active.length)return'FADING';
    if(rec.petitionCount>0)return'STIRRING';
    return'DORMANT';
  }

  function pushHistory(rec,type,data) {
    var item=Object.assign({id:U.randomId('hist'),type:type,at:U.isoNow()},U.deepClone(data||{}));
    rec.history.push(item);if(rec.history.length>250)rec.history=rec.history.slice(-250);rec.updatedAt=item.at;return item;
  }

  function journalActionCount(type){return S.state.session.actions.filter(function(a){return a.type===type;}).length;}


  function overlapHours(aStart,aEnd,bStart,bEnd){var start=Math.max(aStart,bStart),end=Math.min(aEnd,bEnd);return Math.max(0,(end-start)/3600000);}
  function effectActive(rec,key,nowMs){var e=rec.riteEffects&&rec.riteEffects[key];if(!e)return false;var until=typeof e==='string'?new Date(e).getTime():new Date(e.until||0).getTime();return until>Number(nowMs||Date.now());}
  function actionTypeMap(){var out={};(S.state.session.actions||[]).forEach(function(a){out[a.type]=true;});return out;}
  function riteCatalog(){return(window.LYCHGATE_LORE&&window.LYCHGATE_LORE.rites)||[];}
  function riteDefinition(id){var found=null;riteCatalog().some(function(r){if(r.id===id){found=r;return true;}return false;});return found;}
  function ownVigils(rec,faction){decayVigils(rec);return(rec.vigils||[]).filter(function(v){return v.faction===faction&&v.currentCondition>1;});}
  function recentRite(rec,id,minutes){var cutoff=Date.now()-(minutes||30)*60000;return(rec.rites||[]).some(function(r){return r.riteId===id&&new Date(r.at).getTime()>cutoff;});}

  function relicForThreshold(thresholdId){var r=S.state.relics&&S.state.relics[thresholdId];return r?S.ensureRelic(r,thresholdId,S.state):null;}
  function relicRarityRank(r){return{common:1,uncommon:2,rare:3,exceptional:4}[r&&r.rarity]||1;}
  function relicConditionLabel(score){score=Number(score);return score>=85?'sound':score>=60?'worn':score>=35?'faded':'fractured';}
  function pushRelicHistory(relic,type,note,data){var h=Object.assign({id:U.randomId('relic-hist'),type:type,at:U.isoNow(),note:U.safeText(note||'',180)},U.deepClone(data||{}));relic.history.push(h);if(relic.history.length>120)relic.history=relic.history.slice(-120);return h;}
  function linkEndpoints(link){return{a:getThresholdById(link.a,[]),b:getThresholdById(link.b,[])};}
  function maxLinkRangeM(){return[0,900,1500,2400,3800,6000,9000,14000,22000][U.clamp(Number(S.state.player.degree)||1,1,8)];}
  function orient(a,b,c){return(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);}
  function segmentsCrossGeo(a,b,c,d){var o=U.localMeters(a,b),c0=U.localMeters(a,c),d0=U.localMeters(a,d),aa={x:0,y:0};function sign(v){return Math.abs(v)<.000001?0:v>0?1:-1;}return sign(orient(aa,o,c0))*sign(orient(aa,o,d0))<0&&sign(orient(c0,d0,aa))*sign(orient(c0,d0,o))<0;}
  function segmentTouchesExclusion(a,b){var steps=Math.max(12,Math.min(80,Math.ceil(U.distanceM(a,b)/75)));for(var i=1;i<steps;i+=1){var t=i/steps,p={lat:U.lerp(a.lat,b.lat,t),lon:U.lerp(a.lon,b.lon,t)};if(W.isExcluded(p,S.state.world.geometry))return true;}return false;}
  function decayLink(link,nowMs){link=S.ensureLink(link);nowMs=Number(nowMs)||Date.now();var last=new Date(link.lastEvaluatedAt||link.createdAt).getTime();if(!isFinite(last))last=nowMs;var hours=Math.max(0,(nowMs-last)/3600000),distanceFactor=1+Math.min(1.2,(Number(link.distanceM)||0)/12000),loss=hours*(Number(link.decayPerHour)||.18)*distanceFactor;link.stability=U.clamp(Number(link.stability)-loss,0,100);link.strength=U.clamp(Number(link.strength)-loss*.42,0,100);link.lastEvaluatedAt=new Date(nowMs).toISOString();return link;}
  function activeLink(link,nowMs){decayLink(link,nowMs);if(link.stability<=5)return false;var a=stateFor(link.a),b=stateFor(link.b);return factionFromVigils(a)===link.faction&&factionFromVigils(b)===link.faction;}
  function shroudOverlap(a,b){for(var i=0;i<a.points.length;i+=1)if(U.pointInPolygon(a.points[i],b.points))return true;for(var j=0;j<b.points.length;j+=1)if(U.pointInPolygon(b.points[j],a.points))return true;for(var x=0;x<3;x+=1)for(var y=0;y<3;y+=1)if(segmentsCrossGeo(a.points[x],a.points[(x+1)%3],b.points[y],b.points[(y+1)%3]))return true;return false;}

  var G={
    selectedThreshold:null,lastNearby:[],

    selectThreshold:function(t){this.selectedThreshold=U.deepClone(t);var rec=stateFor(t.id);rec.snapshot=thresholdSnapshot(t);if(!rec.discoveredAt){rec.discoveredAt=U.isoNow();pushHistory(rec,'discovered',{source:t.provenance||'deterministic'});S.addAction('discover',{thresholdId:t.id,thresholdName:t.name,kind:t.kind});}S.markDirty();},

    nearby:function(){var fix=S.state.position.fix;if(!fix)return[];var list=W.thresholdsNear(fix,S.state.ui.rangeM||1000,S.state.world.salt,S.state.world.geometry),self=this;list.forEach(function(t){var rec=stateFor(t.id);rec.snapshot=thresholdSnapshot(t);t.faction=factionFromVigils(rec);t.state=thresholdState(rec);t.vigilCount=activeVigils(rec).length;t.bestSigil=rec.bestSigil||0;t.selected=self.selectedThreshold&&self.selectedThreshold.id===t.id;});this.lastNearby=list;return list;},

    currentSafety:function(threshold){var fix=S.state.position.fix;if(!fix)return{locked:true,reason:'No position fix is active.'};if(isFinite(fix.speed)&&fix.speed>U.SPEED_GATE_MPS)return{locked:true,reason:'Interaction is disabled above 25 km/h. Stop moving before working a threshold.'};if(W.isExcluded(fix,S.state.world.geometry))return{locked:true,reason:'The current fix is inside a mapped exclusion zone. Move to safe, legal ground.'};if(threshold){var d=U.distanceM(fix,threshold);if(d>U.INTERACTION_RANGE_M)return{locked:true,reason:'Move within '+U.INTERACTION_RANGE_M+' m of the threshold on safe, legal ground.'};if(threshold.kind==='churchyard'||threshold.kind==='cemetery'){var h=new Date().getHours();if(h>=20||h<7)return{locked:true,reason:'Quiet hours are active here from 20:00 to 07:00. Return during daylight or early evening.'};}}return{locked:false,reason:''};},

    chooseFaction:function(faction){if(['kindled','sextons'].indexOf(faction)<0)throw new Error('Unknown order.');if(S.state.player.faction)throw new Error('An order has already been chosen.');S.state.player.faction=faction;S.addAction('faction',{faction:faction});S.markDirty();},

    defect:function(){if(!S.state.player.faction)throw new Error('Choose an order first.');if(S.state.player.defected)throw new Error('The one permitted defection has already been used.');var old=S.state.player.faction;if(Object.keys(S.state.relics||{}).length)S.softArchive('defection-relics','Relics surrendered on defection',U.deepClone(S.state.relics));if((S.state.links||[]).length)S.softArchive('defection-links','Ley lines surrendered on defection',U.deepClone(S.state.links));S.state.player.faction=old==='kindled'?'sextons':'kindled';S.state.player.defected=true;S.state.player.aether=Math.floor(S.state.player.aether/2);S.state.relics={};S.state.links=[];S.state.player.practiceScore=Math.max(0,S.state.player.practiceScore-75);S.addAction('defection',{from:old,to:S.state.player.faction});S.markDirty();return S.state.player.faction;},

    petition:function(threshold){requireFaction();var safe=this.currentSafety(threshold);if(safe.locked)throw new Error(safe.reason);var rec=stateFor(threshold.id);rec.snapshot=thresholdSnapshot(threshold);var seed=U.hash32(threshold.id+'|petition|'+rec.petitionCount+'|'+S.state.player.id),rng=U.mulberry32(seed),effect=W.featureEffect(threshold.kind);var boost=1,boostNotes=[];if(effectActive(rec,'invitationUntil')){boost*=1.25;boostNotes.push('invitation');}if(effectActive(rec,'passageUntil')){boost*=1.35;boostNotes.push('passage');}var base=6+Math.floor(rng()*9),aether=Math.max(1,Math.round(base*(effect.aether||1)*boost));rec.petitionCount+=1;S.state.player.aether+=aether;var relicChance=.30+Math.min(.18,(threshold.latent&&threshold.latent.depth||1)*.018)+(effectActive(rec,'invitationUntil') ? .08 : 0);var gotRelic=rng()<relicChance;if(gotRelic&&!S.state.relics[threshold.id]){var foundAt=U.isoNow(),raw={id:'relic-'+threshold.id,thresholdId:threshold.id,thresholdName:threshold.name,foundAt:foundAt,kind:threshold.kind,condition:'sound',conditionScore:100,provenance:'petition',factionAtFinding:S.state.player.faction,rarity:['common','common','uncommon','rare','exceptional'][Math.floor(rng()*5)],inscription:['a scored ring','three pinpricks','a split cross','a ladder of four cuts','a crescent nick','a barred eye','two opposing chevrons','a tiny eight-point star'][Math.floor(rng()*8)],resonance:20+Math.floor(rng()*81),attunement:0,attunedFaction:null,transferCount:0,history:[{id:U.randomId('relic-hist'),type:'found',at:foundAt,note:'Recovered by petition at '+threshold.name+'.'}]};S.state.relics[threshold.id]=S.ensureRelic(raw,threshold.id,S.state);}var answer=threshold.latent&&threshold.latent.answer||'The place gives no answer.';pushHistory(rec,'petition',{faction:S.state.player.faction,aether:aether,relic:gotRelic,answer:answer,riteBoost:boostNotes});practice(4,'Petitioned '+threshold.name);S.addAction('petition',{thresholdId:threshold.id,thresholdName:threshold.name,aether:aether,relic:gotRelic,answer:answer,riteBoost:boostNotes});S.markDirty();return{aether:aether,relic:gotRelic,answer:answer,effect:effect.label,riteBoost:boostNotes};},

    setVigil:function(threshold){requireFaction();var safe=this.currentSafety(threshold);if(safe.locked)throw new Error(safe.reason);var rec=stateFor(threshold.id);rec.snapshot=thresholdSnapshot(threshold);decayVigils(rec);var cost=8;if(S.state.player.aether<cost)throw new Error('Eight aether are required to set a vigil.');var own=rec.vigils.filter(function(v){return v.faction===S.state.player.faction;});var slot=-1;for(var i=0;i<8;i+=1){if(!rec.vigils.some(function(v){return v.slot===i&&v.currentCondition>1;})){slot=i;break;}}var tended=false;if(slot<0&&own.length){own.sort(function(a,b){return a.currentCondition-b.currentCondition;});var target=own[0];slot=target.slot;rec.vigils=rec.vigils.filter(function(v){return v!==target;});tended=true;}if(slot<0)throw new Error('All eight vigil positions are occupied. Use an offensive rite to make room.');S.state.player.aether-=cost;var condition=100;rec.vigils.push({slot:slot,faction:S.state.player.faction,condition:condition,currentCondition:condition,setAt:U.isoNow()});pushHistory(rec,tended?'vigil-tended':'vigil',{faction:S.state.player.faction,slot:slot});practice(tended?3:6,(tended?'Tended':'Set')+' vigil at '+threshold.name);S.addAction('vigil',{thresholdId:threshold.id,thresholdName:threshold.name,slot:slot,tended:tended});S.markDirty();return{slot:slot,tended:tended};},

    offense:function(threshold,rite){requireFaction();if(['bell','book','candle'].indexOf(rite)<0)throw new Error('Unknown rite.');var safe=this.currentSafety(threshold);if(safe.locked)throw new Error(safe.reason);var rec=stateFor(threshold.id);decayVigils(rec);var cost={bell:10,book:13,candle:8}[rite];if(S.state.player.aether<cost)throw new Error(cost+' aether are required for this rite.');var enemies=rec.vigils.filter(function(v){return v.faction!==S.state.player.faction&&v.currentCondition>1;});if(!enemies.length)throw new Error('There are no opposing vigils here.');S.state.player.aether-=cost;var damage={bell:18,book:24,candle:30};if(rite==='bell')enemies.forEach(function(v){v.condition=U.clamp(v.currentCondition-damage[rite],0,100);v.currentCondition=v.condition;v.setAt=U.isoNow();});else if(rite==='book')enemies.sort(function(a,b){return b.currentCondition-a.currentCondition;}).slice(0,2).forEach(function(v){v.condition=U.clamp(v.currentCondition-damage[rite]*1.6,0,100);v.currentCondition=v.condition;v.setAt=U.isoNow();});else enemies.sort(function(a,b){return a.currentCondition-b.currentCondition;}).slice(0,3).forEach(function(v){v.condition=U.clamp(v.currentCondition-damage[rite],0,100);v.currentCondition=v.condition;v.setAt=U.isoNow();});rec.vigils=rec.vigils.filter(function(v){return v.currentCondition>1;});pushHistory(rec,'offense',{faction:S.state.player.faction,rite:rite});practice(5,'Used '+rite+' at '+threshold.name);S.addAction('offense',{thresholdId:threshold.id,thresholdName:threshold.name,rite:rite,affected:enemies.length});S.markDirty();return{affected:enemies.length,remaining:rec.vigils.filter(function(v){return v.faction!==S.state.player.faction;}).length};},

    recordSigil:function(threshold,score,detail){detail=detail||{};score=U.clamp(Math.round(score),0,100);var record={id:U.randomId('sigil'),at:U.isoNow(),score:score,name:U.safeText(detail.name||'Unknown sigil',80),family:U.safeText(detail.family||'unknown',40),difficulty:Number(detail.difficulty)||1,practice:!!detail.practice,shape:Number(detail.shape)||0,order:Number(detail.order)||0,direction:Number(detail.direction)||0};if(detail.practice){S.state.player.sigilPracticeHistory.push(record);if(S.state.player.sigilPracticeHistory.length>100)S.state.player.sigilPracticeHistory=S.state.player.sigilPracticeHistory.slice(-100);S.addAction('sigil-practice',{score:score,name:record.name,difficulty:record.difficulty});S.markDirty();return{score:score,aether:0,perfect:score===100};}var safe=this.currentSafety(threshold);if(safe.locked)throw new Error(safe.reason);var rec=stateFor(threshold.id);rec.sigilHistory.push(record);if(rec.sigilHistory.length>100)rec.sigilHistory=rec.sigilHistory.slice(-100);rec.bestSigil=Math.max(rec.bestSigil||0,score);pushHistory(rec,'sigil',{score:score,name:record.name});var bonus=score===100?8:score>=95?4:0,aether=Math.floor(score/10)+bonus;S.state.player.aether+=aether;practice(Math.max(1,Math.floor(score/20))+(score>=95?2:0),'Traced sigil at '+threshold.name);S.addAction('sigil',{thresholdId:threshold.id,thresholdName:threshold.name,score:score,aether:aether,name:record.name,perfect:score===100});S.markDirty();return{score:score,aether:aether,perfect:score===100};},

    addThresholdNote:function(threshold,text){if(!threshold)throw new Error('Select a threshold first.');text=U.safeText(text,1200);if(!text)throw new Error('Write an observation first.');var rec=stateFor(threshold.id),note={id:U.randomId('obs'),at:U.isoNow(),text:text,provenance:'manually recorded'};rec.notes.push(note);pushHistory(rec,'observation',{text:text,provenance:'manually recorded'});S.addAction('observation',{thresholdId:threshold.id,thresholdName:threshold.name,text:text});S.markDirty();return note;},

    addThresholdPhoto:function(threshold,photo){if(!threshold)throw new Error('Select a threshold first.');var rec=stateFor(threshold.id);photo={id:U.randomId('photo'),at:U.isoNow(),name:U.safeText(photo.name||'Field photograph',100),type:U.safeText(photo.type||'image/*',60),dataUrl:String(photo.dataUrl||''),bytes:Number(photo.bytes)||0,provenance:'manually recorded'};rec.photos.push(photo);pushHistory(rec,'photo',{photoId:photo.id,name:photo.name,provenance:'manually recorded'});S.addAction('photo',{thresholdId:threshold.id,thresholdName:threshold.name,name:photo.name});S.markDirty();return photo;},

    archiveThresholdPhoto:function(threshold,photoId){var rec=stateFor(threshold.id),idx=rec.photos.findIndex(function(p){return p.id===photoId;});if(idx<0)return false;var p=rec.photos.splice(idx,1)[0];S.softArchive('threshold-photo',threshold.name+' photo',p);pushHistory(rec,'photo-archived',{photoId:photoId});return true;},


    loreForThreshold:function(threshold){if(!threshold)return null;return W.loreForThreshold(threshold,S.state.world.salt);},

    encounterContext:function(fix){var near=W.thresholdsNear(fix,240,S.state.world.salt,S.state.world.geometry),t=near[0]||null,rec=t?stateFor(t.id):null;return{kind:t?t.kind:'generic',thresholdId:t?t.id:null,thresholdName:t?t.name:null,faction:S.state.player.faction,degree:S.state.player.degree,aether:S.state.player.aether,actionCount:(S.state.session.actions||[]).length,actionTypes:actionTypeMap(),invited:!!(rec&&effectActive(rec,'invitationUntil'))};},

    maybeEncounter:function(fix,nowMs){if(!fix||!isFinite(fix.lat)||!isFinite(fix.lon))return null;if(isFinite(fix.speed)&&fix.speed>3.4)return null;if(W.isExcluded(fix,S.state.world.geometry))return null;nowMs=Number(nowMs)||Date.now();var key=W.geohashEncode(fix.lat,fix.lon,7)+'|'+Math.floor(nowMs/(30*60*1000));if(S.state.encounterKeys[key])return null;S.state.encounterKeys[key]=new Date(nowMs).toISOString();var keys=Object.keys(S.state.encounterKeys);if(keys.length>700){keys.sort(function(a,b){return new Date(S.state.encounterKeys[a]).getTime()-new Date(S.state.encounterKeys[b]).getTime();});keys.slice(0,keys.length-600).forEach(function(k){delete S.state.encounterKeys[k];});}var ctx=this.encounterContext(fix),enc=W.encounterCandidate(fix,nowMs,S.state.world.salt,ctx);if(!enc){S.markDirty();return null;}enc.thresholdId=ctx.thresholdId;enc.thresholdName=ctx.thresholdName;enc.position={lat:U.round(fix.lat,6),lon:U.round(fix.lon,6)};enc.source=fix.source||S.state.position.source||'manual';enc.simulated=!!fix.simulated;enc.order=S.state.player.faction||null;enc.reading=S.state.player.faction==='kindled'?enc.kindled:S.state.player.faction==='sextons'?enc.sextons:'Neither order has interpreted this encounter yet.';S.state.encounters.push(enc);if(S.state.encounters.length>250)S.state.encounters=S.state.encounters.slice(-250);S.state.player.encounterHistory.push({id:enc.id,type:enc.type,title:enc.title,at:enc.at,thresholdId:enc.thresholdId,simulated:enc.simulated});if(S.state.player.encounterHistory.length>250)S.state.player.encounterHistory=S.state.player.encounterHistory.slice(-250);S.state.ui.dismissedEncounterId=null;S.addAction('encounter',{id:enc.id,title:enc.title,type:enc.type,thresholdName:enc.thresholdName||'',kind:enc.kind,simulated:enc.simulated,reading:enc.reading});S.markDirty();return enc;},

    latestEncounter:function(){return S.state.encounters&&S.state.encounters.length?S.state.encounters[S.state.encounters.length-1]:null;},

    riteStatus:function(threshold,riteId){var r=riteDefinition(riteId);if(!r)return{available:false,reason:'Unknown rite.'};if(!threshold)return{available:false,reason:'Select a Threshold first.'};if(!S.state.player.faction)return{available:false,reason:'Choose an order first.'};if(r.order!=='neutral'&&r.order!==S.state.player.faction)return{available:false,reason:'This rite belongs to the other order.'};if(S.state.player.degree<r.degree)return{available:false,reason:'Degree '+r.degree+' is required.'};var safe=this.currentSafety(threshold);if(safe.locked)return{available:false,reason:safe.reason};if(S.state.player.aether<r.cost)return{available:false,reason:r.cost+' aether are required.'};var rec=stateFor(threshold.id),own=ownVigils(rec,S.state.player.faction);if(recentRite(rec,riteId,20))return{available:false,reason:'This rite was worked here recently.'};if(riteId==='witness'&&rec.petitionCount<1)return{available:false,reason:'Petition this Threshold first.'};if(riteId==='watch'&&!activeVigils(rec).length)return{available:false,reason:'At least one active Vigil is required.'};if((riteId==='light'||riteId==='seal')&&!own.length)return{available:false,reason:'At least one Vigil of your order is required.'};if((riteId==='invitation'||riteId==='binding')&&(rec.petitionCount<1||rec.bestSigil<60))return{available:false,reason:'Petition the Threshold and record a Sigil score of 60 or better.'};if((riteId==='passage'||riteId==='reckoning'||riteId==='interment')&&factionFromVigils(rec)!==S.state.player.faction)return{available:false,reason:'Your order must hold this Threshold.'};if(riteId==='passage'&&!S.state.relics[threshold.id])return{available:false,reason:'A Relic from this Threshold is required.'};if(riteId==='vigil'&&own.length<5)return{available:false,reason:'Five Kindled Vigils are required.'};if(riteId==='reckoning'&&(rec.history||[]).filter(function(h){return h.type!=='discovered';}).length<3)return{available:false,reason:'At least three recorded actions are required.'};if(riteId==='interment'&&own.length<6)return{available:false,reason:'Six Sexton Vigils are required.'};if(riteId==='interment'&&Number(S.state.player.inventory.ash||0)<1)return{available:false,reason:'One packet of cold ash is required.'};return{available:true,reason:'Ready.',definition:r};},

    performRite:function(threshold,riteId){requireFaction();var status=this.riteStatus(threshold,riteId);if(!status.available)throw new Error(status.reason);var r=status.definition||riteDefinition(riteId),rec=stateFor(threshold.id),now=Date.now(),iso=new Date(now).toISOString(),own=ownVigils(rec,S.state.player.faction),message='The rite is entered in the ledger.',practiceAward=4;S.state.player.aether-=r.cost;
      function strengthen(amount,full){own.forEach(function(v){v.condition=full?100:U.clamp(v.currentCondition+amount,0,100);v.currentCondition=v.condition;v.setAt=iso;});}
      if(riteId==='witness'){var lore=W.loreForThreshold(threshold,S.state.world.salt),w={id:U.randomId('wit'),at:iso,witness:lore.witness,reference:lore.reference};rec.loreWitnesses.push(w);message='The generated account is witnessed in your local ledger.';practiceAward=3;}
      if(riteId==='watch'){decayVigils(rec,now);var avg=activeVigils(rec).reduce(function(a,v){return a+v.currentCondition;},0)/Math.max(1,activeVigils(rec).length);message='Watch recorded at '+Math.round(avg)+'% mean Vigil condition. '+thresholdState(rec)+'.';practiceAward=2;}
      if(riteId==='light'){strengthen(12,false);rec.riteEffects.litUntil=new Date(now+6*3600000).toISOString();message='Kindled Vigils are tended and the Threshold is lit for six hours.';practiceAward=5;}
      if(riteId==='invitation'){rec.riteEffects.invitationUntil=new Date(now+12*3600000).toISOString();message='Invitation remains open for twelve hours. Petitions carry more Aether and encounters may gather more readily.';practiceAward=7;}
      if(riteId==='passage'){S.softArchive('relic-consumed',threshold.name+' Relic released by Passage',U.deepClone(S.state.relics[threshold.id]));delete S.state.relics[threshold.id];rec.riteEffects.passageUntil=new Date(now+24*3600000).toISOString();rec.riteEffects.decayBurden={start:iso,until:new Date(now+24*3600000).toISOString(),faction:'kindled',multiplier:1.15};message='The Relic is released from the Satchel. Passage remains open for twenty four hours, with stronger petitions and faster Vigil decay.';practiceAward=12;}
      if(riteId==='vigil'){rec.riteEffects.decayGuard={start:iso,until:new Date(now+12*3600000).toISOString(),faction:'kindled',multiplier:.80};message='The open door is watched for twelve hours. Kindled Vigil decay is reduced.';practiceAward=7;}
      if(riteId==='seal'){strengthen(12,false);rec.riteEffects.sealedUntil=new Date(now+6*3600000).toISOString();message='Sexton Vigils are tended and the measured edge is sealed for six hours.';practiceAward=5;}
      if(riteId==='binding'){rec.riteEffects.decayGuard={start:iso,until:new Date(now+12*3600000).toISOString(),faction:'sextons',multiplier:.68};message='The pattern is bound for twelve hours. Sexton Vigil decay is reduced.';practiceAward=7;}
      if(riteId==='reckoning'){var count=(rec.history||[]).filter(function(h){return h.type!=='discovered';}).length;practiceAward=Math.min(14,6+count);message='The reckoning enters '+count+' prior actions and the current ownership state into the ledger.';rec.riteEffects.reckonedAt=iso;}
      if(riteId==='interment'){S.state.player.inventory.ash=Math.max(0,Number(S.state.player.inventory.ash||0)-1);strengthen(0,true);rec.riteEffects.decayGuard={start:iso,until:new Date(now+24*3600000).toISOString(),faction:'sextons',multiplier:.55};message='Cold ash is spent. Sexton Vigils are restored and strongly guarded for twenty four hours.';practiceAward=14;}
      var entry={id:U.randomId('rite'),riteId:riteId,name:r.name,order:r.order,at:iso,cost:r.cost,practice:practiceAward,message:message};rec.rites.push(entry);if(rec.rites.length>120)rec.rites=rec.rites.slice(-120);S.state.player.riteHistory.push({id:entry.id,riteId:riteId,name:r.name,thresholdId:threshold.id,thresholdName:threshold.name,at:iso,cost:r.cost,practice:practiceAward});if(S.state.player.riteHistory.length>300)S.state.player.riteHistory=S.state.player.riteHistory.slice(-300);pushHistory(rec,'rite',{riteId:riteId,name:r.name,order:r.order,cost:r.cost,message:message});practice(practiceAward,'Worked '+r.name+' at '+threshold.name);S.addAction('rite',{thresholdId:threshold.id,thresholdName:threshold.name,riteId:riteId,name:r.name,cost:r.cost,practice:practiceAward,message:message});S.markDirty();return entry;},

    riteCatalog:function(){return riteCatalog().slice();},

    thresholdFaction:function(id){return factionFromVigils(stateFor(id));},
    thresholdState:function(id){return thresholdState(stateFor(id));},

    ownedThresholds:function(faction){faction=faction||S.state.player.faction;return Object.keys(S.state.thresholds).map(function(id){var rec=stateFor(id);return{id:id,record:rec,snapshot:rec.snapshot};}).filter(function(x){return x.snapshot&&faction&&factionFromVigils(x.record)===faction;});},

    relics:function(){return Object.keys(S.state.relics||{}).map(function(k){return S.ensureRelic(S.state.relics[k],k,S.state);});},
    relicForThreshold:function(id){return relicForThreshold(id);},
    attuneRelic:function(id){requireFaction();var relic=S.state.relics[id]||this.relics().filter(function(r){return r.id===id;})[0];if(!relic)throw new Error('Relic not found.');var t=getThresholdById(relic.thresholdId,this.lastNearby);if(!t)throw new Error('The Relic origin is not present in the local ledger.');var safe=this.currentSafety(t);if(safe.locked)throw new Error('Attunement must be worked at the originating Threshold. '+safe.reason);var cost=8+relicRarityRank(relic)*2;if(S.state.player.aether<cost)throw new Error(cost+' aether are required to attune this Relic.');S.state.player.aether-=cost;var gain=18+relicRarityRank(relic)*4;relic.attunement=U.clamp(relic.attunement+gain,0,100);relic.attunedFaction=S.state.player.faction;relic.conditionScore=U.clamp(relic.conditionScore-2,0,100);relic.condition=relicConditionLabel(relic.conditionScore);pushRelicHistory(relic,'attuned','Attuned to '+S.state.player.faction+' at '+relic.thresholdName+'.',{gain:gain,cost:cost});practice(4,'Attuned a Relic');S.addAction('relic-attune',{relicId:relic.id,thresholdId:relic.thresholdId,thresholdName:relic.thresholdName,attunement:relic.attunement,cost:cost});S.markDirty();return relic;},
    makeRelicStone:function(id){var relic=S.state.relics[id]||this.relics().filter(function(r){return r.id===id;})[0];if(!relic)throw new Error('Relic not found.');var copy=U.deepClone(relic);copy.transferCount=Math.max(0,Number(copy.transferCount)||0)+1;copy.history=Array.isArray(copy.history)?copy.history:[];copy.history.push({id:U.randomId('relic-hist'),type:'transferred-out',at:U.isoNow(),note:'Prepared as a Passage Stone transfer.'});var payload={schema:'LYCHGATE_RELIC_1',relic:copy,actor:S.state.player.id,actorOrder:S.state.player.faction,at:U.isoNow()},env={payload:payload,signer:S.state.identity.signer};env.signature=U.simpleSignature(payload,env.signer);S.softArchive('relic-transfer',relic.thresholdName+' Relic transferred out',U.deepClone(relic));delete S.state.relics[relic.thresholdId];S.addAction('relic-transfer-out',{relicId:relic.id,thresholdId:relic.thresholdId,thresholdName:relic.thresholdName,transferCount:copy.transferCount});S.markDirty();return'LYCHGATE-RELIC-1\n'+btoa(unescape(encodeURIComponent(JSON.stringify(env))))+'\nEND-LYCHGATE-RELIC';},
    importRelicStone:function(text){var clean=String(text||'').trim(),match=clean.match(/^LYCHGATE-RELIC-1\s+([A-Za-z0-9+/=]+)\s+END-LYCHGATE-RELIC$/);if(!match)throw new Error('Relic stone framing is invalid.');var env;try{env=JSON.parse(decodeURIComponent(escape(atob(match[1]))));}catch(e){throw new Error('Relic stone payload could not be decoded.');}if(!env||!env.payload||env.payload.schema!=='LYCHGATE_RELIC_1'||!env.payload.relic)throw new Error('Relic stone schema is invalid.');if(U.simpleSignature(env.payload,env.signer)!==env.signature)throw new Error('Relic stone signature does not match its payload.');var incoming=S.ensureRelic(U.deepClone(env.payload.relic),env.payload.relic.thresholdId,S.state),existing=relicForThreshold(incoming.thresholdId);if(existing){var inAt=new Date(incoming.history&&incoming.history.length?incoming.history[incoming.history.length-1].at:env.payload.at).getTime(),exAt=new Date(existing.history&&existing.history.length?existing.history[existing.history.length-1].at:existing.foundAt).getTime();if(inAt<=exAt)throw new Error('A newer or equal Relic record from this Threshold is already in the Satchel.');S.softArchive('relic-conflict',existing.thresholdName+' older Relic record',existing);}incoming.transferCount=Math.max(1,Number(incoming.transferCount)||1);pushRelicHistory(incoming,'transferred-in','Imported from '+U.safeText(env.signer,80)+'.');S.state.relics[incoming.thresholdId]=incoming;S.state.importedStones.push({importedAt:U.isoNow(),signer:U.safeText(env.signer,120),thresholdId:incoming.thresholdId,signature:env.signature,type:'relic-transfer'});S.addAction('relic-transfer-in',{relicId:incoming.id,thresholdId:incoming.thresholdId,thresholdName:incoming.thresholdName,transferCount:incoming.transferCount});S.markDirty();return{type:'relic',thresholdId:incoming.thresholdId,name:incoming.thresholdName};},

    maxLinkRangeM:function(){return maxLinkRangeM();},
    linkSurvey:function(fromThreshold,toId){var to=getThresholdById(toId,this.lastNearby);if(!fromThreshold||!to)return{ok:false,reason:'Both Threshold records are required.'};var distance=U.distanceM(fromThreshold,to),maxRange=maxLinkRangeM(),crossings=[],self=this;(S.state.links||[]).forEach(function(l){if(l.a===fromThreshold.id||l.b===fromThreshold.id||l.a===toId||l.b===toId)return;if(!activeLink(l))return;var ep=linkEndpoints(l);if(ep.a&&ep.b&&segmentsCrossGeo(fromThreshold,to,ep.a,ep.b))crossings.push(l);});var exclusion=segmentTouchesExclusion(fromThreshold,to),geometry=S.state.world.geometry&&Array.isArray(S.state.world.geometry.features),visibility=!geometry?'UNVERIFIED':exclusion?'BLOCKED':distance>maxRange*.82?'LONG':'CLEAR',clearance=U.clamp(Math.round(100-(distance/maxRange)*42-crossings.length*30-(exclusion?70:0)),0,100);var relic=relicForThreshold(toId),cost=Math.max(8,Math.round(10+distance/1000*2-((fromThreshold.kind==='crossroads'||to.kind==='crossroads')?2:0)));return{ok:distance<=maxRange&&!exclusion&&!crossings.length,distanceM:distance,maxRangeM:maxRange,rangeOk:distance<=maxRange,exclusionCrossing:exclusion,crossingLinks:crossings,visibility:visibility,clearance:clearance,cost:cost,relic:relic,reason:distance>maxRange?'Range exceeds Degree '+S.state.player.degree+' limit.':exclusion?'The proposed line crosses mapped excluded ground.':crossings.length?'Ley lines may not cross an existing active line.':'Survey is clear.'};},
    createLink:function(fromThreshold,toId){requireFaction();if(!fromThreshold||!toId||fromThreshold.id===toId)throw new Error('Choose two different Thresholds.');var originSafety=this.currentSafety(fromThreshold);if(originSafety.locked)throw new Error(originSafety.reason);if(this.thresholdFaction(fromThreshold.id)!==S.state.player.faction||this.thresholdFaction(toId)!==S.state.player.faction)throw new Error('Both Thresholds must be held by your order.');var relic=relicForThreshold(toId);if(!relic)throw new Error('A Relic for the destination Threshold is required.');if(Number(relic.conditionScore)<20)throw new Error('The destination Relic is too fractured to carry a Ley line.');var exists=S.state.links.some(function(l){return(l.a===fromThreshold.id&&l.b===toId)||(l.a===toId&&l.b===fromThreshold.id);});if(exists)throw new Error('Those Thresholds are already joined.');var survey=this.linkSurvey(fromThreshold,toId);if(!survey.ok)throw new Error(survey.reason);if(S.state.player.aether<survey.cost)throw new Error(survey.cost+' aether are required to draw this ley line.');S.state.player.aether-=survey.cost;var now=U.isoNow(),resonance=(Number(relic.resonance)||0)+(relic.attunedFaction===S.state.player.faction?Number(relic.attunement)||0:0),initial=U.clamp(Math.round(78+survey.clearance*.12+resonance*.08),45,100),link=S.ensureLink({id:U.randomId('line'),a:fromThreshold.id,b:toId,faction:S.state.player.faction,createdAt:now,distanceM:survey.distanceM,stability:initial,strength:initial,decayPerHour:.14+Math.min(.24,survey.distanceM/50000),lastEvaluatedAt:now,relicId:relic.id,survey:{visibility:survey.visibility,clearance:survey.clearance,maxRangeM:survey.maxRangeM,cost:survey.cost},history:[{id:U.randomId('line-hist'),type:'drawn',at:now,note:'Drawn with '+relic.thresholdName+' Relic at '+Math.round(initial)+'% stability.'}]});S.state.links.push(link);relic.conditionScore=U.clamp(relic.conditionScore-1,0,100);relic.condition=relicConditionLabel(relic.conditionScore);pushRelicHistory(relic,'line-drawn','Used as destination proof for a '+U.formatDistance(link.distanceM)+' Ley line.');practice(8,'Drew ley line');S.addAction('link',{from:fromThreshold.name,to:getThresholdById(toId,this.lastNearby).name,fromId:fromThreshold.id,toId:toId,distanceM:link.distanceM,stability:link.stability,cost:survey.cost});S.markDirty();return link;},
    decayLinks:function(nowMs){(S.state.links||[]).forEach(function(l){decayLink(l,nowMs);});return S.state.links;},
    reinforceLink:function(linkId){requireFaction();var link=(S.state.links||[]).filter(function(l){return l.id===linkId;})[0];if(!link)throw new Error('Ley line not found.');decayLink(link);if(link.faction!==S.state.player.faction)throw new Error('Only a line of your order can be reinforced.');if(this.thresholdFaction(link.a)!==S.state.player.faction||this.thresholdFaction(link.b)!==S.state.player.faction)throw new Error('Both endpoints must still be held by your order.');var ep=linkEndpoints(link),fix=S.state.position.fix;if(!ep.a||!ep.b||!fix)throw new Error('A position fix and both Threshold records are required.');var nearA=U.distanceM(fix,ep.a)<=U.INTERACTION_RANGE_M,nearB=U.distanceM(fix,ep.b)<=U.INTERACTION_RANGE_M;if(!nearA&&!nearB)throw new Error('Stand within '+U.INTERACTION_RANGE_M+' m of either endpoint to reinforce this line.');var safe=this.currentSafety(nearA?ep.a:ep.b);if(safe.locked)throw new Error(safe.reason);var cost=Math.max(5,Math.round(5+link.distanceM/2500));if(S.state.player.aether<cost)throw new Error(cost+' aether are required to reinforce this line.');S.state.player.aether-=cost;var gain=U.clamp(24+S.state.player.degree*2,0,40),before=link.stability;link.stability=U.clamp(link.stability+gain,0,100);link.strength=U.clamp(link.strength+gain*.8,0,100);link.reinforcedAt=U.isoNow();link.reinforcementCount+=1;link.lastEvaluatedAt=link.reinforcedAt;link.history.push({id:U.randomId('line-hist'),type:'reinforced',at:link.reinforcedAt,note:'Reinforced from '+(nearA?ep.a.name:ep.b.name)+'.',from:Math.round(before),to:Math.round(link.stability),cost:cost});practice(4,'Reinforced ley line');S.addAction('link-reinforce',{linkId:link.id,from:Math.round(before),to:Math.round(link.stability),cost:cost});S.markDirty();return link;},
    archiveCollapsedLinks:function(){var keep=[];(S.state.links||[]).forEach(function(l){decayLink(l);if(l.stability<=5){S.softArchive('collapsed-ley-line','Collapsed Ley line '+l.id,l);S.addAction('link-collapse',{linkId:l.id,reason:'stability exhausted'});}else keep.push(l);});S.state.links=keep;return keep;},

    computeAllShrouds:function(nowMs){this.decayLinks(nowMs);var byFaction={kindled:{},sextons:{}};Object.keys(S.state.thresholds||{}).forEach(function(id){var rec=stateFor(id),f=factionFromVigils(rec);if(f&&rec.snapshot)byFaction[f][id]=rec.snapshot;});var out=[],self=this;['kindled','sextons'].forEach(function(faction){var byId=byFaction[faction],edges={},edgeObjs={};(S.state.links||[]).forEach(function(l){if(l.faction!==faction||!byId[l.a]||!byId[l.b]||!activeLink(l,nowMs))return;var key=[l.a,l.b].sort().join('|');edges[key]=true;edgeObjs[key]=l;});var ids=Object.keys(byId).sort();for(var i=0;i<ids.length;i+=1)for(var j=i+1;j<ids.length;j+=1)for(var k=j+1;k<ids.length;k+=1){var a=ids[i],b=ids[j],c=ids[k],ab=[a,b].sort().join('|'),ac=[a,c].sort().join('|'),bc=[b,c].sort().join('|');if(edges[ab]&&edges[ac]&&edges[bc]){var points=[byId[a],byId[b],byId[c]],area=U.triangleAreaM2(points[0],points[1],points[2]);if(area<=5)continue;var sid='shroud-'+faction+'-'+[a,b,c].sort().join('-'),links=[edgeObjs[ab],edgeObjs[ac],edgeObjs[bc]],base=Math.min.apply(null,links.map(function(l){return l.stability;})),rec=S.state.shroudRecords[sid]||{id:sid,faction:faction,firstRaisedAt:U.isoNow(),lastSeenAt:null,lastCollectedAt:U.isoNow(),totalAether:0,history:[]};if(rec.collapsedAt){rec.history.push({type:'raised-again',at:U.isoNow(),note:'The triangle closed again.'});delete rec.collapsedAt;delete rec.collapseReason;rec.lastCollectedAt=U.isoNow();}rec.lastSeenAt=U.isoNow();S.state.shroudRecords[sid]=rec;out.push({id:sid,ids:[a,b,c],points:points,areaM2:area,faction:faction,links:links,ageMs:Math.max(0,Date.now()-new Date(rec.firstRaisedAt).getTime()),stability:U.clamp(base,0,100),record:rec,nesting:0,overlaps:[],productionPerHour:0});}}});out.forEach(function(s){out.forEach(function(o){if(s===o)return;if(s.faction===o.faction&&U.pointInPolygon(U.centroid(s.points),o.points)&&o.areaM2>s.areaM2)s.nesting+=1;if(s.faction!==o.faction&&shroudOverlap(s,o))s.overlaps.push(o.id);});s.stability=U.clamp(s.stability+s.nesting*3-s.overlaps.length*12,0,100);s.productionPerHour=(s.areaM2/1000000)*(.45+s.stability/100*.55)*(1+s.nesting*.12);});var active={};out.forEach(function(s){active[s.id]=true;});Object.keys(S.state.shroudRecords).forEach(function(id){var r=S.state.shroudRecords[id];if(!active[id]&&!r.collapsedAt){r.collapsedAt=U.isoNow();r.collapseReason='An edge collapsed, an endpoint changed hands, or the triangle no longer closes.';r.history.push({type:'collapsed',at:r.collapsedAt,note:r.collapseReason});}});return out;},
    computeShrouds:function(faction,nowMs){faction=faction||S.state.player.faction;return this.computeAllShrouds(nowMs).filter(function(s){return faction&&s.faction===faction;});},
    groundDominance:function(){var all=this.computeAllShrouds(),totals={kindled:0,sextons:0},stable={kindled:0,sextons:0};all.forEach(function(s){totals[s.faction]+=s.areaM2;stable[s.faction]+=s.areaM2*(s.stability/100);});var leader=stable.kindled===stable.sextons?'balanced':stable.kindled>stable.sextons?'kindled':'sextons';return{areas:totals,weighted:stable,leader:leader,unsettled:Math.max(0,Math.abs(totals.kindled-totals.sextons)),shrouds:all};},
    groundProduction:function(nowMs){nowMs=Number(nowMs)||Date.now();var faction=S.state.player.faction,sh=this.computeShrouds(faction,nowMs),total=0,detail=[];sh.forEach(function(s){var last=new Date(s.record.lastCollectedAt||s.record.firstRaisedAt).getTime(),hours=U.clamp((nowMs-last)/3600000,0,36),amount=s.productionPerHour*hours*(s.stability/100);if(amount>0){total+=amount;detail.push({id:s.id,hours:hours,amount:amount});}});return{amount:Math.floor(total),raw:total,detail:detail};},
    collectGroundAether:function(){requireFaction();var now=Date.now(),p=this.groundProduction(now);if(p.amount<1)throw new Error('The held ground has not gathered a full unit of Aether yet.');p.detail.forEach(function(d){var r=S.state.shroudRecords[d.id];if(r){r.lastCollectedAt=new Date(now).toISOString();r.totalAether=(Number(r.totalAether)||0)+d.amount;r.history.push({type:'harvest',at:r.lastCollectedAt,note:'Ground yielded '+d.amount.toFixed(2)+' Aether.'});}});S.state.player.aether+=p.amount;S.addAction('ground-harvest',{aether:p.amount,shrouds:p.detail.length});practice(Math.min(8,Math.max(1,Math.floor(p.amount/3))),'Collected Aether from held ground');S.markDirty();return p.amount;},
    scoreGround:function(){return Math.round(this.computeShrouds().reduce(function(sum,s){return sum+Math.sqrt(s.areaM2)*(s.stability/100)*(1+s.nesting*.08);},0));},

    degreeRequirement:function(degree){var thresholds=[0,40,100,200,350,550,800,1100];return thresholds[U.clamp(degree-1,0,7)];},
    advanceDegree:function(){var current=S.state.player.degree;if(current>=8)throw new Error('Degree Eight is the highest Degree of Sight.');var needed=this.degreeRequirement(current+1);if(S.state.player.practiceScore<needed)throw new Error('The next rite requires '+needed+' practice score.');var count=Object.keys(S.state.thresholds).filter(function(id){return(stateFor(id).bestSigil||0)>=60;}).length;if(count<current)throw new Error('The rite requires at least '+current+' thresholds with sigil scores of 60 or better.');S.state.player.degree+=1;S.addAction('advancement',{degree:S.state.player.degree});S.markDirty();return S.state.player.degree;},

    makeStone:function(threshold){if(!threshold)throw new Error('Select a threshold first.');var rec=stateFor(threshold.id);var payload={schema:'LYCHGATE_STONE_1',threshold:{id:threshold.id,name:threshold.name,lat:threshold.lat,lon:threshold.lon,kind:threshold.kind},record:{vigils:rec.vigils,petitionCount:rec.petitionCount,bestSigil:rec.bestSigil,updatedAt:rec.updatedAt},faction:factionFromVigils(rec),actor:S.state.player.id,actorOrder:S.state.player.faction,at:rec.updatedAt||U.isoNow()};var env={payload:payload,signer:S.state.identity.signer};env.signature=U.simpleSignature(payload,env.signer);return'LYCHGATE-STONE-1\n'+btoa(unescape(encodeURIComponent(JSON.stringify(env))))+'\nEND-LYCHGATE-STONE';},

    importStone:function(text){var clean=String(text||'').trim(),match=clean.match(/^LYCHGATE-STONE-1\s+([A-Za-z0-9+/=]+)\s+END-LYCHGATE-STONE$/);if(!match)throw new Error('Passage stone framing is invalid.');var env;try{env=JSON.parse(decodeURIComponent(escape(atob(match[1]))));}catch(e){throw new Error('Passage stone payload could not be decoded.');}if(!env||!env.payload||env.payload.schema!=='LYCHGATE_STONE_1')throw new Error('Passage stone schema is invalid.');if(U.simpleSignature(env.payload,env.signer)!==env.signature)throw new Error('Passage stone signature does not match its payload.');var p=env.payload,t=p.threshold;if(!t||!t.id||!isFinite(t.lat)||!isFinite(t.lon))throw new Error('Passage stone threshold is invalid.');var rec=stateFor(U.safeText(t.id,120)),incomingAt=new Date(p.record&&p.record.updatedAt||p.at||0).getTime(),localAt=new Date(rec.updatedAt||0).getTime(),conflict=null;if(incomingAt>localAt){if(rec.updatedAt)conflict={winner:'incoming',loser:U.deepClone({record:rec,at:rec.updatedAt})};rec.snapshot={id:U.safeText(t.id,120),name:U.safeText(t.name,120),lat:Number(t.lat),lon:Number(t.lon),kind:U.safeText(t.kind,40),provenance:'passage stone'};rec.provenance='passage stone';rec.vigils=Array.isArray(p.record.vigils)?p.record.vigils.slice(0,8).map(function(v,idx){return{slot:idx,faction:v.faction==='kindled'?'kindled':'sextons',condition:U.clamp(Number(v.condition)||0,0,100),currentCondition:U.clamp(Number(v.condition)||0,0,100),setAt:v.setAt||p.at};}):[];rec.petitionCount=Math.max(0,Number(p.record.petitionCount)||0);rec.bestSigil=U.clamp(Number(p.record.bestSigil)||0,0,100);rec.updatedAt=p.record.updatedAt||p.at;}else conflict={winner:'local',loser:{record:U.deepClone(p.record),at:p.record&&p.record.updatedAt}};if(conflict)rec.history.push({type:'stone-conflict',at:U.isoNow(),winner:conflict.winner,loser:conflict.loser,provenance:'passage stone'});else pushHistory(rec,'stone-import',{provenance:'passage stone'});S.state.importedStones.push({importedAt:U.isoNow(),signer:U.safeText(env.signer,120),thresholdId:t.id,signature:env.signature,conflictWinner:conflict?conflict.winner:'incoming'});S.addAction('stone-import',{thresholdId:t.id,signer:env.signer,conflict:conflict?conflict.winner:'none'});S.markDirty();return{thresholdId:t.id,name:t.name,conflict:conflict?conflict.winner:'none'};},

    journalStats:function(session){session=session||S.state.session;var actions=session.actions||[],fixes=S.state.position.history||[],start=new Date(session.startedAt).getTime(),end=session.endedAt?new Date(session.endedAt).getTime():Date.now();var distance=0;for(var i=1;i<fixes.length;i+=1){var a=fixes[i-1],b=fixes[i];if(new Date(a.at).getTime()>=start&&new Date(b.at).getTime()<=end){var d=U.distanceM(a,b);if(d<250)distance+=d;}}var cells={},discoveries={};fixes.forEach(function(f){var tm=new Date(f.at).getTime();if(tm>=start&&tm<=end)cells[W.geohashEncode(f.lat,f.lon,5)]=true;});actions.forEach(function(a){if(a.type==='discover'&&a.data&&a.data.thresholdId)discoveries[a.data.thresholdId]=true;});return{number:session.number||1,durationMs:Math.max(0,end-start),distanceM:distance,regions:Object.keys(cells).length,thresholdsDiscovered:Object.keys(discoveries).length,petitions:actions.filter(function(a){return a.type==='petition';}).length,sigils:actions.filter(function(a){return a.type==='sigil';}).length,vigils:actions.filter(function(a){return a.type==='vigil';}).length,attacks:actions.filter(function(a){return a.type==='offense';}).length,rites:actions.filter(function(a){return a.type==='rite';}).length,encounters:actions.filter(function(a){return a.type==='encounter';}).length,lines:actions.filter(function(a){return a.type==='link';}).length,shrouds:this.computeShrouds().length,notes:(session.notes||[]).length,fixes:fixes.filter(function(f){var tm=new Date(f.at).getTime();return tm>=start&&tm<=end;}).length};},

    fieldReport:function(){var shrouds=this.computeShrouds(),dom=this.groundDominance(),prod=this.groundProduction();return{session:S.state.session,journal:this.journalStats(),faction:S.state.player.faction,degree:S.state.player.degree,aether:S.state.player.aether,held:this.ownedThresholds().length,links:S.state.links.filter(function(l){return l.stability>5;}).length,shrouds:shrouds.length,groundScore:this.scoreGround(),groundArea:dom.areas,groundWeighted:dom.weighted,groundLeader:dom.leader,groundAetherReady:prod.amount};},

    stateFor:stateFor,decayVigils:decayVigils,factionFromVigils:factionFromVigils,getThresholdById:getThresholdById,thresholdStateFor:thresholdState
  };

  window.LG_GAME=G;
}());
