/* LYCHGATE :: identity.js :: v5.3.0 */
(function () {
  'use strict';

  var U=window.LG_UTIL,S=window.LG_STORAGE;
  var METHOD='ECDSA-P256-SHA256';
  var BACKUP_SCHEMA='LYCHGATE_IDENTITY_BACKUP_1';
  var PUBLIC_SCHEMA='LYCHGATE_PUBLIC_IDENTITY_1';
  var cache={privateKey:null,publicKey:null,fingerprint:null,keyId:null};

  function subtle(){return window.crypto&&window.crypto.subtle?window.crypto.subtle:null;}
  function bytesToB64(bytes){var a=new Uint8Array(bytes),s='',i;for(i=0;i<a.length;i+=1)s+=String.fromCharCode(a[i]);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'');}
  function b64ToBytes(text){var b=String(text||'').replace(/-/g,'+').replace(/_/g,'/');while(b.length%4)b+='=';var s=atob(b),a=new Uint8Array(s.length),i;for(i=0;i<s.length;i+=1)a[i]=s.charCodeAt(i);return a;}
  function utf8(text){return new TextEncoder().encode(String(text==null?'':text));}
  function fingerprintText(hex){var groups=[];for(var i=0;i<32;i+=4)groups.push(hex.slice(i,i+4).toUpperCase());return groups.join(' ');}
  function publicShape(jwk){return{kty:jwk.kty,crv:jwk.crv,x:jwk.x,y:jwk.y};}
  async function fingerprintFor(jwk){var d=await subtle().digest('SHA-256',utf8(U.stableStringify(publicShape(jwk)))),a=new Uint8Array(d),hex='';for(var i=0;i<a.length;i+=1)hex+=a[i].toString(16).padStart(2,'0');return fingerprintText(hex);}
  function keyIdFromFingerprint(fp){return 'lgid-'+String(fp||'').replace(/\s/g,'').slice(0,16).toLowerCase();}
  function blankIdentity(legacySigner){return{schema:'LYCHGATE_IDENTITY_1',status:'pending',algorithm:METHOD,createdAt:null,keyId:null,fingerprint:null,publicJwk:null,privateJwk:null,retiredKeys:[],legacySigner:legacySigner||'',lastError:null};}
  function stateIdentity(){if(!S.state.identity||S.state.identity.schema!=='LYCHGATE_IDENTITY_1'){var old=S.state.identity||{};S.state.identity=blankIdentity(old.signer||old.legacySigner||'');}S.state.identity.retiredKeys=Array.isArray(S.state.identity.retiredKeys)?S.state.identity.retiredKeys:[];return S.state.identity;}
  async function importCache(){var id=stateIdentity(),c=subtle();if(!c||!id.publicJwk||!id.privateJwk)return false;cache.publicKey=await c.importKey('jwk',id.publicJwk,{name:'ECDSA',namedCurve:'P-256'},true,['verify']);cache.privateKey=await c.importKey('jwk',id.privateJwk,{name:'ECDSA',namedCurve:'P-256'},true,['sign']);cache.fingerprint=id.fingerprint;cache.keyId=id.keyId;return true;}
  async function generate(reason){var c=subtle(),id=stateIdentity();if(!c){id.status='unavailable';id.lastError='WebCrypto SubtleCrypto is unavailable in this browser context.';S.markDirty();return id;}var pair=await c.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),pub=await c.exportKey('jwk',pair.publicKey),priv=await c.exportKey('jwk',pair.privateKey),fp=await fingerprintFor(pub);if(id.publicJwk&&id.fingerprint){id.retiredKeys.push({keyId:id.keyId,fingerprint:id.fingerprint,publicJwk:id.publicJwk,createdAt:id.createdAt,retiredAt:U.isoNow(),reason:reason||'rotation'});if(id.retiredKeys.length>12)id.retiredKeys=id.retiredKeys.slice(-12);}id.schema='LYCHGATE_IDENTITY_1';id.status='ready';id.algorithm=METHOD;id.createdAt=U.isoNow();id.keyId=keyIdFromFingerprint(fp);id.fingerprint=fp;id.publicJwk=pub;id.privateJwk=priv;id.lastError=null;cache.privateKey=pair.privateKey;cache.publicKey=pair.publicKey;cache.fingerprint=fp;cache.keyId=id.keyId;S.markDirty();return id;}
  async function ensure(){var id=stateIdentity();if(id.status==='ready'&&id.publicJwk&&id.privateJwk){try{await importCache();return id;}catch(e){id.lastError=U.safeText(e.message,300);}}try{return await generate('initial generation');}catch(err){id.status='unavailable';id.lastError=U.safeText(err.message,300);S.markDirty();return id;}}
  function publicCard(){var id=stateIdentity();return{schema:PUBLIC_SCHEMA,keyId:id.keyId||null,fingerprint:id.fingerprint||null,algorithm:id.algorithm||METHOD,publicJwk:id.publicJwk?JSON.parse(JSON.stringify(id.publicJwk)):null,playerId:U.safeText(S.state.player.id,120),callSign:U.safeText(S.state.player.callSign||'Walker',80),faction:S.state.player.faction||null,degree:U.clamp(Number(S.state.player.degree)||1,1,8),createdAt:id.createdAt||null};}
  async function signPayload(payload){var id=stateIdentity(),c=subtle();if(!c||id.status!=='ready'||!id.privateJwk)throw new Error(id.lastError||'Cryptographic identity is unavailable.');if(!cache.privateKey||cache.keyId!==id.keyId)await importCache();var sig=await c.sign({name:'ECDSA',hash:'SHA-256'},cache.privateKey,utf8(U.stableStringify(payload)));return{method:METHOD,keyId:id.keyId,fingerprint:id.fingerprint,publicJwk:JSON.parse(JSON.stringify(id.publicJwk)),signature:bytesToB64(sig)};}
  async function verifyPayload(payload,integrity){var c=subtle();if(!integrity||integrity.method!==METHOD||!integrity.publicJwk||!integrity.signature)return{valid:false,reason:'Missing ECDSA verification material.',method:integrity&&integrity.method||'unknown'};if(!c)return{valid:false,reason:'WebCrypto is unavailable, so this signature cannot be verified here.',method:METHOD,unavailable:true};try{var fp=await fingerprintFor(integrity.publicJwk);if(integrity.fingerprint&&fp!==integrity.fingerprint)return{valid:false,reason:'Public-key fingerprint does not match the artifact fingerprint.',method:METHOD,fingerprint:fp};var key=await c.importKey('jwk',integrity.publicJwk,{name:'ECDSA',namedCurve:'P-256'},true,['verify']),valid=await c.verify({name:'ECDSA',hash:'SHA-256'},key,b64ToBytes(integrity.signature),utf8(U.stableStringify(payload)));return{valid:!!valid,reason:valid?'ECDSA signature verified.':'ECDSA signature verification failed.',method:METHOD,fingerprint:fp,keyId:integrity.keyId||keyIdFromFingerprint(fp)};}catch(e){return{valid:false,reason:'Signature verification failed: '+U.safeText(e.message,220),method:METHOD};}}
  async function deriveBackupKey(passphrase,salt,uses){var base=await subtle().importKey('raw',utf8(passphrase),'PBKDF2',false,['deriveKey']);return subtle().deriveKey({name:'PBKDF2',salt:salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,uses);}
  async function exportBackup(passphrase){passphrase=String(passphrase||'');if(passphrase.length<8)throw new Error('Use a backup passphrase of at least 8 characters.');var id=stateIdentity(),c=subtle();if(!c||id.status!=='ready')throw new Error('Cryptographic identity is unavailable.');var salt=new Uint8Array(16),iv=new Uint8Array(12);window.crypto.getRandomValues(salt);window.crypto.getRandomValues(iv);var key=await deriveBackupKey(passphrase,salt,['encrypt']),plain={schema:'LYCHGATE_IDENTITY_SECRET_1',identity:JSON.parse(JSON.stringify(id)),player:{id:S.state.player.id,callSign:S.state.player.callSign},exportedAt:U.isoNow()},cipher=await c.encrypt({name:'AES-GCM',iv:iv},key,utf8(JSON.stringify(plain))),pack={schema:BACKUP_SCHEMA,version:1,kdf:'PBKDF2-SHA256',iterations:180000,cipher:'AES-256-GCM',salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(cipher)};return 'LYCHGATE-IDENTITY-BACKUP-1\n'+U.utf8ToBase64Url(JSON.stringify(pack));}
  async function importBackup(text,passphrase){var c=subtle();if(!c)throw new Error('WebCrypto is unavailable.');var raw=String(text||'').trim();if(raw.indexOf('LYCHGATE-IDENTITY-BACKUP-1')!==0)throw new Error('Unrecognized identity backup.');var line=raw.split(/\r?\n/)[1];if(!line)throw new Error('Identity backup data is missing.');var pack=JSON.parse(U.base64UrlToUtf8(line));if(pack.schema!==BACKUP_SCHEMA)throw new Error('Unsupported identity backup schema.');var key=await deriveBackupKey(String(passphrase||''),b64ToBytes(pack.salt),['decrypt']),plainBytes;try{plainBytes=await c.decrypt({name:'AES-GCM',iv:b64ToBytes(pack.iv)},key,b64ToBytes(pack.data));}catch(e){throw new Error('Backup could not be decrypted. Check the passphrase.');}var plain=JSON.parse(new TextDecoder().decode(plainBytes)),incoming=plain.identity;if(!incoming||!incoming.publicJwk||!incoming.privateJwk)throw new Error('Backup does not contain a complete identity.');var fp=await fingerprintFor(incoming.publicJwk);if(fp!==incoming.fingerprint)throw new Error('Backup public-key fingerprint is inconsistent.');var current=stateIdentity();if(current.publicJwk&&current.fingerprint&&current.fingerprint!==incoming.fingerprint){current.retiredKeys.push({keyId:current.keyId,fingerprint:current.fingerprint,publicJwk:current.publicJwk,createdAt:current.createdAt,retiredAt:U.isoNow(),reason:'replaced by encrypted backup'});incoming.retiredKeys=(incoming.retiredKeys||[]).concat(current.retiredKeys).slice(-12);}S.state.identity=incoming;S.state.identity.status='ready';S.markDirty();await importCache();return S.state.identity;}
  async function rotate(){return generate('manual rotation');}
  function status(){var id=stateIdentity();return{available:!!subtle(),ready:id.status==='ready'&&!!id.publicJwk&&!!id.privateJwk,status:id.status,fingerprint:id.fingerprint,keyId:id.keyId,algorithm:id.algorithm,lastError:id.lastError,retiredCount:(id.retiredKeys||[]).length};}

  window.LG_IDENTITY={method:METHOD,publicSchema:PUBLIC_SCHEMA,backupSchema:BACKUP_SCHEMA,ensure:ensure,rotate:rotate,publicCard:publicCard,signPayload:signPayload,verifyPayload:verifyPayload,fingerprintFor:fingerprintFor,exportBackup:exportBackup,importBackup:importBackup,status:status,bytesToB64:bytesToB64,b64ToBytes:b64ToBytes};
}());
