/* LYCHGATE :: relay.js :: v5.3.0 */
(function(){
  'use strict';
  var U=window.LG_UTIL,S=window.LG_STORAGE;
  var R={transport:null,status:'disconnected',onStatus:null,onMessage:null,bc:null,pc:null,dc:null,ws:null,serialPort:null,serialReader:null,serialWriter:null,serialReading:false};
  function ensure(){if(!S.state.relay||typeof S.state.relay!=='object')S.state.relay={inbox:[],outbox:[],settings:{transport:'broadcast',channel:'LYCHGATE-FIELD',wsUrl:'ws://127.0.0.1:8787'}};S.state.relay.inbox=Array.isArray(S.state.relay.inbox)?S.state.relay.inbox:[];S.state.relay.outbox=Array.isArray(S.state.relay.outbox)?S.state.relay.outbox:[];S.state.relay.settings=Object.assign({transport:'broadcast',channel:'LYCHGATE-FIELD',wsUrl:'ws://127.0.0.1:8787'},S.state.relay.settings||{});return S.state.relay;}
  function setStatus(s,detail){R.status=s;if(typeof R.onStatus==='function')R.onStatus(s,detail||'');}
  function log(direction,transport,text,peer){var st=ensure(),row={id:U.randomId('relay'),at:U.isoNow(),direction:direction,transport:transport,chars:String(text||'').length,peer:U.safeText(peer||'',120),preview:U.safeText(String(text||'').slice(0,160),180)};(direction==='in'?st.inbox:st.outbox).push(row);if(st.inbox.length>200)st.inbox=st.inbox.slice(-200);if(st.outbox.length>200)st.outbox=st.outbox.slice(-200);S.markDirty();return row;}
  function receive(text,transport,peer){text=String(text||'');if(!text)return;log('in',transport,text,peer);if(typeof R.onMessage==='function')R.onMessage(text,{transport:transport,peer:peer||'',at:U.isoNow()});}
  function wireDataChannel(dc){R.dc=dc;dc.onopen=function(){setStatus('connected','WebRTC data channel open.');};dc.onclose=function(){setStatus('disconnected','WebRTC data channel closed.');};dc.onerror=function(){setStatus('error','WebRTC data channel error.');};dc.onmessage=function(e){receive(e.data,'webrtc','direct peer');};}
  function waitIce(pc){return new Promise(function(resolve){if(pc.iceGatheringState==='complete')return resolve();var timer=setTimeout(resolve,3500);function done(){if(pc.iceGatheringState==='complete'){clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',done);resolve();}}pc.addEventListener('icegatheringstatechange',done);});}
  function makePc(){if(!window.RTCPeerConnection)throw new Error('WebRTC is unavailable in this browser context.');if(R.pc)try{R.pc.close();}catch(e){}var pc=new RTCPeerConnection({iceServers:[]});R.pc=pc;pc.onconnectionstatechange=function(){var s=pc.connectionState;if(s==='connected')setStatus('connected','Direct WebRTC peer connected.');else if(['failed','closed','disconnected'].indexOf(s)>=0)setStatus(s==='failed'?'error':'disconnected','WebRTC '+s+'.');};pc.ondatachannel=function(e){wireDataChannel(e.channel);};return pc;}
  async function createOffer(){var pc=makePc(),dc=pc.createDataChannel('lychgate',{ordered:true});wireDataChannel(dc);var offer=await pc.createOffer();await pc.setLocalDescription(offer);await waitIce(pc);setStatus('signaling','Offer ready for manual exchange.');return JSON.stringify(pc.localDescription);}
  async function applySignal(text){var desc=JSON.parse(String(text||''));if(!desc||['offer','answer'].indexOf(desc.type)<0)throw new Error('Remote signal must be a WebRTC offer or answer.');if(desc.type==='offer'){var pc=makePc();await pc.setRemoteDescription(desc);var answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitIce(pc);setStatus('signaling','Answer ready. Return it to the offering peer.');return JSON.stringify(pc.localDescription);}if(!R.pc)throw new Error('Create an offer before applying an answer.');await R.pc.setRemoteDescription(desc);setStatus('connecting','Answer accepted. Waiting for peer connection.');return '';} 
  function connectBroadcast(name){disconnect();name=U.safeText(name||'LYCHGATE-FIELD',80)||'LYCHGATE-FIELD';if(!window.BroadcastChannel)throw new Error('BroadcastChannel is unavailable.');R.bc=new BroadcastChannel(name);R.bc.onmessage=function(e){receive(e.data,'broadcast',name);};R.transport='broadcast';ensure().settings.channel=name;ensure().settings.transport='broadcast';S.markDirty();setStatus('connected','Local channel '+name+' open.');return true;}
  async function connectWebSocket(url){disconnect();url=String(url||'').trim();if(!/^wss?:\/\//i.test(url))throw new Error('Enter a ws:// or wss:// endpoint.');return await new Promise(function(resolve,reject){var ws=new WebSocket(url),done=false;R.ws=ws;ws.onopen=function(){done=true;R.transport='websocket';ensure().settings.wsUrl=url;ensure().settings.transport='websocket';S.markDirty();setStatus('connected','WebSocket companion connected.');resolve(true);};ws.onmessage=function(e){receive(e.data,'websocket',url);};ws.onerror=function(){if(!done)reject(new Error('WebSocket connection failed.'));else setStatus('error','WebSocket error.');};ws.onclose=function(){setStatus('disconnected','WebSocket companion disconnected.');};});}
  async function connectSerial(){disconnect();if(!navigator.serial)throw new Error('Web Serial is unavailable.');var port=await navigator.serial.requestPort();await port.open({baudRate:115200});R.serialPort=port;R.transport='serial';ensure().settings.transport='serial';S.markDirty();R.serialReading=true;setStatus('connected','Serial text bridge open at 115200 baud.');(async function(){var decoder=new TextDecoder(),buf='';try{while(R.serialReading&&port.readable){var reader=port.readable.getReader();R.serialReader=reader;try{while(R.serialReading){var rr=await reader.read();if(rr.done)break;buf+=decoder.decode(rr.value,{stream:true});var lines=buf.split(/\r?\n/);buf=lines.pop();lines.forEach(function(line){if(line.indexOf('LYCHGATE-RELAY-1|')===0){try{receive(U.base64UrlToUtf8(line.slice(17)),'serial','serial bridge');}catch(e){}}});}}finally{reader.releaseLock();R.serialReader=null;}if(!R.serialReading)break;}}catch(e){if(R.serialReading)setStatus('error','Serial read failed: '+e.message);}}());return true;}
  async function send(text){text=String(text||'');if(!text)throw new Error('Prepare an artifact before sending.');if(R.transport==='broadcast'&&R.bc)R.bc.postMessage(text);else if(R.transport==='webrtc'&&R.dc&&R.dc.readyState==='open')R.dc.send(text);else if(R.transport==='websocket'&&R.ws&&R.ws.readyState===1)R.ws.send(text);else if(R.transport==='serial'&&R.serialPort&&R.serialPort.writable){var writer=R.serialPort.writable.getWriter();try{await writer.write(new TextEncoder().encode('LYCHGATE-RELAY-1|'+U.utf8ToBase64Url(text)+'\n'));}finally{writer.releaseLock();}}else throw new Error('The selected peer relay is not connected.');log('out',R.transport,text,R.transport);return true;}
  function activateWebRtc(){R.transport='webrtc';ensure().settings.transport='webrtc';S.markDirty();setStatus(R.dc&&R.dc.readyState==='open'?'connected':'signaling','WebRTC manual signaling selected.');}
  function disconnect(){if(R.bc){R.bc.close();R.bc=null;}if(R.dc){try{R.dc.close();}catch(e){}R.dc=null;}if(R.pc){try{R.pc.close();}catch(e){}R.pc=null;}if(R.ws){try{R.ws.close();}catch(e){}R.ws=null;}R.serialReading=false;if(R.serialReader){try{R.serialReader.cancel();}catch(e){}}if(R.serialPort){try{R.serialPort.close();}catch(e){}R.serialPort=null;}R.transport=null;setStatus('disconnected','Relay closed.');}
  function logs(){var st=ensure();return{inbox:st.inbox.slice().reverse(),outbox:st.outbox.slice().reverse(),settings:st.settings};}
  window.LG_RELAY={ensure:ensure,connectBroadcast:connectBroadcast,createOffer:createOffer,applySignal:applySignal,activateWebRtc:activateWebRtc,connectWebSocket:connectWebSocket,connectSerial:connectSerial,send:send,disconnect:disconnect,logs:logs,receiveForTest:receive,get status(){return R.status;},get transport(){return R.transport;},get onStatus(){return R.onStatus;},set onStatus(fn){R.onStatus=fn;},get onMessage(){return R.onMessage;},set onMessage(fn){R.onMessage=fn;}};
}());
