/* LYCHGATE :: scenarios.js :: v5.3.0
   Finite local scenario authoring and runtime.
   Scenario definitions may contain fictional narrative and local coordinates. They never imply historical fact.
*/
(function(){
  'use strict';
  var U=window.LG_UTIL,S=window.LG_STORAGE;
  var TYPES=['clue','location','threshold','action','rite','sigil','relic','choice','encounter','ending'];

  function store(){
    S.state.scenarios=S.state.scenarios&&typeof S.state.scenarios==='object'?S.state.scenarios:{items:{},order:[],active:null,completions:[]};
    S.state.scenarios.items=S.state.scenarios.items&&typeof S.state.scenarios.items==='object'?S.state.scenarios.items:{};
    S.state.scenarios.order=Array.isArray(S.state.scenarios.order)?S.state.scenarios.order:[];
    S.state.scenarios.completions=Array.isArray(S.state.scenarios.completions)?S.state.scenarios.completions:[];
    if(S.state.scenarios.active&&(!S.state.scenarios.active.scenarioId||!S.state.scenarios.items[S.state.scenarios.active.scenarioId]))S.state.scenarios.active=null;
    return S.state.scenarios;
  }
  function safePoint(obj){if(!obj||!isFinite(obj.lat)||!isFinite(obj.lon))return null;return{lat:U.clamp(Number(obj.lat),-90,90),lon:U.clamp(Number(obj.lon),-180,180)};}
  function safeTime(v){v=String(v||'').trim();return /^([01]\d|2[0-3]):[0-5]\d$/.test(v)?v:'';}
  function sanitizeStrokeData(value){
    if(!Array.isArray(value))return null;
    var out=value.slice(0,8).map(function(st){return Array.isArray(st)?st.slice(0,120).map(function(p){return{x:U.clamp(Number(p&&p.x)||0,0,1),y:U.clamp(Number(p&&p.y)||0,0,1)};}):[];}).filter(function(st){return st.length>=2;});
    return out.length?out:null;
  }
  function sanitizeChoice(c){return{label:U.safeText(c&&c.label||'Choose',100),next:U.safeText(c&&c.next||'',80)};}
  function sanitizeNode(n,index){
    n=n&&typeof n==='object'?n:{};var type=TYPES.indexOf(n.type)>=0?n.type:'clue',p=safePoint(n);
    return{id:U.safeText(n.id||('node-'+(index+1)),80),title:U.safeText(n.title||('Step '+(index+1)),140),type:type,text:U.safeText(n.text||'',3000),lat:p?p.lat:null,lon:p?p.lon:null,radiusM:U.clamp(Number(n.radiusM)||40,5,5000),thresholdId:U.safeText(n.thresholdId||'',120),actionType:U.safeText(n.actionType||'',80),riteId:U.safeText(n.riteId||'',80),sigilMinScore:U.clamp(Number(n.sigilMinScore)||70,0,100),relicThresholdId:U.safeText(n.relicThresholdId||'',120),timeStart:safeTime(n.timeStart),timeEnd:safeTime(n.timeEnd),next:U.safeText(n.next||'',80),choices:Array.isArray(n.choices)?n.choices.slice(0,4).map(sanitizeChoice):[],endingCode:U.safeText(n.endingCode||'',100),encounterTitle:U.safeText(n.encounterTitle||'',140),customSigil:n.customSigil&&typeof n.customSigil==='object'?{name:U.safeText(n.customSigil.name||'Scenario mark',100),family:U.safeText(n.customSigil.family||'scenario',60),difficulty:U.clamp(Number(n.customSigil.difficulty)||3,1,5),revealMs:U.clamp(Number(n.customSigil.revealMs)||1800,500,8000),strokes:sanitizeStrokeData(n.customSigil.strokes)}:null};
  }
  function sanitizeScenario(obj){
    if(!obj||typeof obj!=='object')throw new Error('Scenario must be a JSON object.');
    var bounds=obj.bounds&&typeof obj.bounds==='object'?obj.bounds:{},center=safePoint(bounds.center||bounds),pre=obj.prerequisites&&typeof obj.prerequisites==='object'?obj.prerequisites:{},nodes=Array.isArray(obj.nodes)?obj.nodes.slice(0,200).map(sanitizeNode):[];
    var seen={};nodes.forEach(function(n){if(!n.id||seen[n.id])n.id=U.randomId('node');seen[n.id]=true;});
    var sc={schema:'LYCHGATE_SCENARIO_1',version:'1.0',id:U.safeText(obj.id||U.randomId('scenario'),80),title:U.safeText(obj.title||'Untitled Scenario',160),author:U.safeText(obj.author||'',120),summary:U.safeText(obj.summary||'',1800),startClue:U.safeText(obj.startClue||'',2400),createdAt:obj.createdAt||U.isoNow(),updatedAt:U.isoNow(),provenance:U.safeText(obj.provenance||'Scenario authoring',240),fictionNotice:'Scenario narrative is LYCHGATE fiction, not historical evidence about real places.',bounds:center?{lat:center.lat,lon:center.lon,radiusM:U.clamp(Number(bounds.radiusM)||5000,50,100000)}:null,prerequisites:{minDegree:U.clamp(Number(pre.minDegree)||1,1,8),faction:['kindled','sextons','any'].indexOf(pre.faction)>=0?pre.faction:'any',requiredRelicId:U.safeText(pre.requiredRelicId||'',120),startAt:pre.startAt||'',endAt:pre.endAt||''},firstNodeId:U.safeText(obj.firstNodeId||nodes[0]&&nodes[0].id||'',80),nodes:nodes};
    return sc;
  }
  function create(opts){var st=store(),sc=sanitizeScenario(Object.assign({id:U.randomId('scenario'),createdAt:U.isoNow(),provenance:'Locally authored scenario'},opts||{}));st.items[sc.id]=sc;st.order.push(sc.id);S.addAction('scenario-create',{scenarioId:sc.id,title:sc.title});S.markDirty();return sc;}
  function get(id){return store().items[id]||null;}
  function list(){var st=store();return st.order.map(function(id){return st.items[id];}).filter(Boolean);}
  function update(id,patch){var sc=get(id);if(!sc)throw new Error('Scenario not found.');var merged=Object.assign({},sc,patch||{});merged.id=sc.id;merged.nodes=sc.nodes;var clean=sanitizeScenario(merged);clean.createdAt=sc.createdAt;clean.nodes=sc.nodes;store().items[id]=clean;S.markDirty();return clean;}
  function addNode(id,data){var sc=get(id);if(!sc)throw new Error('Scenario not found.');var node=sanitizeNode(Object.assign({id:U.randomId('node')},data||{}),sc.nodes.length);sc.nodes.push(node);if(!sc.firstNodeId)sc.firstNodeId=node.id;sc.updatedAt=U.isoNow();S.markDirty();return node;}
  function updateNode(id,nodeId,patch){var sc=get(id),idx=sc&&sc.nodes.findIndex(function(n){return n.id===nodeId;});if(!sc||idx<0)throw new Error('Scenario node not found.');var merged=Object.assign({},sc.nodes[idx],patch||{});merged.id=sc.nodes[idx].id;sc.nodes[idx]=sanitizeNode(merged,idx);sc.updatedAt=U.isoNow();S.markDirty();return sc.nodes[idx];}
  function archiveNode(id,nodeId){var sc=get(id),idx=sc&&sc.nodes.findIndex(function(n){return n.id===nodeId;});if(!sc||idx<0)throw new Error('Scenario node not found.');var node=sc.nodes.splice(idx,1)[0];S.softArchive('scenario-node',sc.title+' / '+node.title,node);if(sc.firstNodeId===nodeId)sc.firstNodeId=sc.nodes[0]?sc.nodes[0].id:'';sc.nodes.forEach(function(n){if(n.next===nodeId)n.next='';(n.choices||[]).forEach(function(c){if(c.next===nodeId)c.next='';});});sc.updatedAt=U.isoNow();S.markDirty();return node;}
  function archiveScenario(id){var st=store(),sc=get(id);if(!sc)throw new Error('Scenario not found.');if(st.active&&st.active.scenarioId===id)st.active=null;S.softArchive('scenario',sc.title,sc);delete st.items[id];st.order=st.order.filter(function(x){return x!==id;});S.markDirty();return sc;}
  function validateGraph(sc){sc=sanitizeScenario(sc);var ids={};sc.nodes.forEach(function(n){ids[n.id]=true;});var errors=[];if(!sc.nodes.length)errors.push('Add at least one scenario node.');if(sc.firstNodeId&&!ids[sc.firstNodeId])errors.push('The first node does not exist.');sc.nodes.forEach(function(n){if(n.next&&!ids[n.next])errors.push(n.title+': next node '+n.next+' does not exist.');(n.choices||[]).forEach(function(c){if(c.next&&!ids[c.next])errors.push(n.title+': choice destination '+c.next+' does not exist.');});if(n.type==='location'&&!safePoint(n))errors.push(n.title+': location coordinates are required.');if(n.type==='threshold'&&!n.thresholdId&&!safePoint(n))errors.push(n.title+': Threshold ID or coordinates are required.');if(n.type==='action'&&!n.actionType)errors.push(n.title+': an action type is required.');if(n.type==='rite'&&!n.riteId)errors.push(n.title+': a rite ID is required.');if(n.type==='relic'&&!n.relicThresholdId)errors.push(n.title+': a Relic Threshold ID is required.');if(n.type==='choice'&&!(n.choices||[]).length)errors.push(n.title+': at least one choice is required.');if(n.type==='sigil'&&n.customSigil&&(!n.customSigil.strokes||!n.customSigil.strokes.length))errors.push(n.title+': custom Sigil needs valid strokes.');});return{valid:!errors.length,errors:errors,scenario:sc};}
  function canStart(sc,now){var reasons=[],p=sc.prerequisites||{},fix=S.state.position.fix;now=now||Date.now();if(S.state.player.degree<(p.minDegree||1))reasons.push('Degree '+p.minDegree+' is required.');if(p.faction&&p.faction!=='any'&&S.state.player.faction!==p.faction)reasons.push('This scenario requires '+p.faction+'.');if(p.requiredRelicId&&!S.state.relics[p.requiredRelicId]&&!Object.keys(S.state.relics||{}).some(function(k){return S.state.relics[k].id===p.requiredRelicId;}))reasons.push('Required Relic is not in the Satchel.');if(p.startAt&&new Date(p.startAt).getTime()>now)reasons.push('The scenario has not opened yet.');if(p.endAt&&new Date(p.endAt).getTime()<now)reasons.push('The scenario time window has closed.');if(sc.bounds){if(!fix)reasons.push('Set a position fix inside the scenario region.');else if(U.distanceM(fix,sc.bounds)>sc.bounds.radiusM)reasons.push('Move within '+U.formatDistance(sc.bounds.radiusM)+' of the scenario region.');}return{available:!reasons.length,reasons:reasons};}
  function start(id){var st=store(),sc=get(id),graph=sc&&validateGraph(sc);if(!sc)throw new Error('Scenario not found.');if(!graph.valid)throw new Error(graph.errors[0]);var c=canStart(sc);if(!c.available)throw new Error(c.reasons[0]);if(st.active&&st.active.status==='underway')throw new Error('Another scenario is already underway.');st.active={id:U.randomId('run'),scenarioId:id,status:'underway',currentNodeId:sc.firstNodeId,startedAt:U.isoNow(),updatedAt:U.isoNow(),visited:[],history:[],endingCode:null};st.active.history.push({type:'start',at:st.active.startedAt,nodeId:sc.firstNodeId});S.addAction('scenario-start',{scenarioId:id,title:sc.title});enterCurrent();S.markDirty();return st.active;}
  function current(){var st=store(),a=st.active;if(!a)return null;var sc=get(a.scenarioId);return{run:a,scenario:sc,node:sc&&sc.nodes.filter(function(n){return n.id===a.currentNodeId;})[0]||null};}
  function insideTime(node,now){if(!node.timeStart&&!node.timeEnd)return true;var d=new Date(now||Date.now()),mins=d.getHours()*60+d.getMinutes(),toM=function(s){if(!s)return null;var p=s.split(':');return Number(p[0])*60+Number(p[1]);},a=toM(node.timeStart),b=toM(node.timeEnd);if(a==null)return mins<=b;if(b==null)return mins>=a;if(a<=b)return mins>=a&&mins<=b;return mins>=a||mins<=b;}
  function completeRun(code){var st=store(),a=st.active,sc=a&&get(a.scenarioId);if(!a||!sc)return null;var now=U.isoNow();a.status='completed';a.completedAt=now;a.updatedAt=now;a.endingCode=U.safeText(code||'COMPLETE',100);a.history.push({type:'complete',at:now,endingCode:a.endingCode});var rec={schema:'LYCHGATE_SCENARIO_COMPLETION_1',id:U.randomId('scenario-completion'),scenarioId:sc.id,title:sc.title,runId:a.id,startedAt:a.startedAt,completedAt:now,endingCode:a.endingCode,visited:a.visited.slice(),history:U.deepClone(a.history)};st.completions.push(rec);if(st.completions.length>300)st.completions=st.completions.slice(-300);st.active=null;S.addAction('scenario-complete',{scenarioId:sc.id,title:sc.title,endingCode:rec.endingCode});S.markDirty();return rec;}
  function move(next,reason){var c=current();if(!c||!c.node)return null;var a=c.run,node=c.node,now=U.isoNow();if(a.visited.indexOf(node.id)<0)a.visited.push(node.id);a.history.push({type:'node-complete',at:now,nodeId:node.id,title:node.title,reason:reason||'condition met'});if(!next){if(node.type==='ending'||node.endingCode)return completeRun(node.endingCode||'COMPLETE');next=node.next;}if(!next)return completeRun('COMPLETE');if(!c.scenario.nodes.some(function(n){return n.id===next;}))throw new Error('Scenario destination '+next+' does not exist.');a.currentNodeId=next;a.updatedAt=now;a.history.push({type:'enter',at:now,nodeId:next});S.markDirty();return enterCurrent();}
  function enterCurrent(){var c=current();if(!c||!c.node)return null;var n=c.node;if(n.type==='ending')return completeRun(n.endingCode||n.title||'COMPLETE');if(n.type==='relic'){var has=S.state.relics[n.relicThresholdId]||Object.keys(S.state.relics||{}).some(function(k){return S.state.relics[k].id===n.relicThresholdId;});if(has)return move(n.next,'required Relic carried');}if(n.type==='location')return recordFix(S.state.position.fix);if(n.type==='threshold'&&n.lat!=null)return recordFix(S.state.position.fix);if(n.type==='action'||n.type==='rite'||n.type==='sigil')return null;if(n.type==='clue'||n.type==='choice'||n.type==='encounter')return null;return null;}
  function recordFix(fix){var c=current();if(!c||!c.node||!fix)return null;if(window.LG_GAME&&window.LG_GAME.currentSafety&&window.LG_GAME.currentSafety(null).locked)return null;var n=c.node;if(!insideTime(n,new Date(fix.at||Date.now()).getTime()))return null;if(n.type==='location'&&n.lat!=null&&U.distanceM(fix,n)<=n.radiusM)return move(n.next,'location reached');if(n.type==='threshold'&&n.lat!=null&&U.distanceM(fix,n)<=n.radiusM&&!n.actionType)return move(n.next,'Threshold location reached');return null;}
  function recordAction(action){var c=current();if(!c||!c.node||!action)return null;var n=c.node,d=action.data||{};if(!insideTime(n,new Date(action.at||Date.now()).getTime()))return null;if(n.type==='action'&&action.type===n.actionType&&(!n.thresholdId||d.thresholdId===n.thresholdId))return move(n.next,'action '+action.type);if(n.type==='threshold'&&(!n.thresholdId||d.thresholdId===n.thresholdId)&&(!n.actionType||action.type===n.actionType))return move(n.next,'Threshold objective completed');if(n.type==='rite'&&action.type==='rite'&&d.riteId===n.riteId&&(!n.thresholdId||d.thresholdId===n.thresholdId))return move(n.next,'rite '+n.riteId);if(n.type==='sigil'&&action.type==='sigil'&&Number(d.score)>=n.sigilMinScore&&(!n.thresholdId||d.thresholdId===n.thresholdId)&&(!n.customSigil||!n.customSigil.name||d.name===n.customSigil.name))return move(n.next,'Sigil score '+d.score);if(n.type==='relic'&&(action.type==='relic-transfer-in'||action.type==='relic-attune'||action.type==='petition'))return enterCurrent();return null;}
  function continueNode(){var c=current();if(!c||!c.node)throw new Error('No active scenario node.');if(['clue','encounter'].indexOf(c.node.type)<0)throw new Error('This objective advances from field activity.');return move(c.node.next,'continued by player');}
  function choose(index){var c=current();if(!c||!c.node||c.node.type!=='choice')throw new Error('The current scenario node is not a choice.');var ch=c.node.choices[index];if(!ch)throw new Error('Choice not found.');c.run.history.push({type:'choice',at:U.isoNow(),nodeId:c.node.id,label:ch.label,next:ch.next});return move(ch.next,'choice: '+ch.label);}
  function recordCustomSigil(nodeId,score){var c=current();if(!c||!c.node||c.node.id!==nodeId||c.node.type!=='sigil'||!c.node.customSigil)throw new Error('No custom scenario Sigil is active.');score=U.clamp(Math.round(Number(score)||0),0,100);c.run.history.push({type:'custom-sigil',at:U.isoNow(),nodeId:nodeId,score:score,name:c.node.customSigil.name});S.addAction('scenario-sigil',{scenarioId:c.scenario.id,nodeId:nodeId,name:c.node.customSigil.name,score:score});if(score>=c.node.sigilMinScore)return move(c.node.next,'custom Sigil score '+score);S.markDirty();return{score:score,passed:false};}
  function abandon(){var c=current();if(!c)return null;var a=c.run,sc=c.scenario;a.status='abandoned';a.abandonedAt=U.isoNow();a.history.push({type:'abandon',at:a.abandonedAt,nodeId:a.currentNodeId});S.softArchive('scenario-run',sc.title+' abandoned run',U.deepClone(a));store().active=null;S.addAction('scenario-abandon',{scenarioId:sc.id,title:sc.title});S.markDirty();return a;}
  function exportText(id){var sc=get(id);if(!sc)throw new Error('Scenario not found.');return JSON.stringify(sanitizeScenario(sc),null,2);}
  function importText(text){var raw=JSON.parse(text);if(!raw||raw.schema!=='LYCHGATE_SCENARIO_1')throw new Error('Unsupported Scenario schema.');var sc=sanitizeScenario(raw),gate=validateGraph(sc),st=store();if(!gate.valid)throw new Error(gate.errors[0]);if(st.items[sc.id])S.softArchive('scenario-replaced',st.items[sc.id].title,st.items[sc.id]);st.items[sc.id]=sc;if(st.order.indexOf(sc.id)<0)st.order.push(sc.id);S.markDirty();return sc;}
  function exportable(){return list().map(function(sc){return sanitizeScenario(sc);});}
  function importDefinitions(defs){if(!Array.isArray(defs))return[];var st=store(),added=[];defs.slice(0,100).forEach(function(raw){var gate=validateGraph(raw);if(!gate.valid)return;var sc=gate.scenario;if(st.items[sc.id])S.softArchive('scenario-replaced',st.items[sc.id].title,st.items[sc.id]);st.items[sc.id]=sc;if(st.order.indexOf(sc.id)<0)st.order.push(sc.id);added.push(sc);});S.markDirty();return added;}

  window.LG_SCENARIOS={types:TYPES.slice(),ensureStore:store,sanitizeScenario:sanitizeScenario,sanitizeNode:sanitizeNode,create:create,get:get,list:list,update:update,addNode:addNode,updateNode:updateNode,archiveNode:archiveNode,archiveScenario:archiveScenario,validateGraph:validateGraph,canStart:canStart,start:start,current:current,recordFix:recordFix,recordAction:recordAction,continueNode:continueNode,choose:choose,recordCustomSigil:recordCustomSigil,abandon:abandon,exportText:exportText,importText:importText,exportable:exportable,importDefinitions:importDefinitions};
}());
